  INFO root [0x00003598] [2019-03-01 13:35:21,436] - 
  INFO root [0x00003598] [2019-03-01 13:35:21,437] - -----------------------------------------------------------------------------------------


  INFO root [0x00003598] [2019-03-01 13:35:21,460] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x00003598] [2019-03-01 13:35:21,460] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x00003598] [2019-03-01 13:35:21,461] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x00003598] [2019-03-01 13:35:21,512] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:14711 )
  INFO root [0x00003598] [2019-03-01 13:35:21,512] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:14711, SOMAXCONN=5.
  INFO root [0x00003598] [2019-03-01 13:35:21,512] - server-configs:
  INFO root [0x00003598] [2019-03-01 13:35:21,512] - 	gameUpdateHertz : 10
  INFO root [0x00003598] [2019-03-01 13:35:21,530] - 	defaultViewRadius : 80
  INFO root [0x00003598] [2019-03-01 13:35:21,530] - 	defaultViewHysteresisArea : 5
  INFO root [0x00003598] [2019-03-01 13:35:21,546] - 	entryScriptFile : kbemain
  INFO root [0x00003598] [2019-03-01 13:35:21,546] - 	internalTcpAddr : 192.168.0.148:14711
  INFO root [0x00003598] [2019-03-01 13:35:21,546] - 	componentID : 8001
  WARN root [0x00003598] [2019-03-01 13:35:21,580] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [0x00003598] [2019-03-01 13:35:21,625] - Components::findLogger: found logger, addr:192.168.0.148:14556
  INFO root [0x00003598] [2019-03-01 13:35:21,625] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00003598] [2019-03-01 13:35:21,626] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003598] [2019-03-01 13:35:21,633] - ---- cellapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: E73A667D90DF1EB3CFEA32B1FCE682E5. Config: Debug X86. Built: 17:21:32 Feb 27 2019. AppID: 8001. UID: 28936. PID: 13716 ----
  INFO root [0x00003598] [2019-03-01 13:35:21,634] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x00003598] [2019-03-01 13:35:21,635] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003598] [2019-03-01 13:35:21,635] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00003598] [2019-03-01 13:35:21,871] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00003598] [2019-03-01 13:35:21,871] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003598] [2019-03-01 13:35:22,037] - loaded entity-script:Account(1).
 DEBUG root [0x00003598] [2019-03-01 13:35:22,039] - loaded entity-script:Room(3).
  INFO root [0x00003598] [2019-03-01 13:35:22,040] - TelnetServer server is running on port 50000
  INFO root [0x00003598] [2019-03-01 13:35:22,549] - ---- cellapp is running ----
 DEBUG root [0x00003598] [2019-03-01 13:35:22,550] - Components::process(): Request for the process of identity...
  WARN root [0x00003598] [2019-03-01 13:35:29,187] - Forwarding logs to logger[192.168.0.148:14556/0/0/0]...
 ERROR root [0x00003598] [2019-03-01 13:40:23,480] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00003598] [2019-03-01 13:40:23,484] - The following logs sent to logger failed:
  WARN root [0x00003598] [2019-03-01 13:40:23,485] - ==> [2019-03-01 13:40:23 479] TCPPacketReceiver::processPendingEvents(192.168.0.148:14556): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003598] [2019-03-01 13:40:23,485] - ==> [2019-03-01 13:40:23 482] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [0x00003598] [2019-03-01 13:40:23,519] - TCPPacketReceiver::processPendingEvents(192.168.0.148:14604): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003598] [2019-03-01 13:40:23,520] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00003598] [2019-03-01 13:40:23,553] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00003598] [2019-03-01 13:40:23,553] - Shutdowner::onShutdown: shutting down
 S_DBG root [0x00003598] [2019-03-01 13:40:23,554] - Avatar::onDestroy: 2.
 S_ERR root [0x00003598] [2019-03-01 13:40:23,559] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x00003598] [2019-03-01 13:40:23,560] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
 S_DBG root [0x00003598] [2019-03-01 13:40:23,584] - Avatar::onDestroy: 4.
 S_ERR root [0x00003598] [2019-03-01 13:40:23,584] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x00003598] [2019-03-01 13:40:23,586] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
  INFO root [0x00003598] [2019-03-01 13:40:23,589] - Spaces::destroySpace: 1.
 S_DBG root [0x00003598] [2019-03-01 13:40:23,589] - Avatar::onDestroy: 5.
 S_ERR root [0x00003598] [2019-03-01 13:40:23,590] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x00003598] [2019-03-01 13:40:23,591] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
 S_DBG root [0x00003598] [2019-03-01 13:40:23,593] - Avatar::onDestroy: 7.
 S_ERR root [0x00003598] [2019-03-01 13:40:23,593] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x00003598] [2019-03-01 13:40:23,594] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
  INFO root [0x00003598] [2019-03-01 13:40:23,595] - Spaces::destroySpace: 2.
  INFO root [0x00003598] [2019-03-01 13:40:23,595] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00003598] [2019-03-01 13:40:23,616] - Room::~Room(): 6
 DEBUG root [0x00003598] [2019-03-01 13:40:23,616] - Account::~Account(): 5
 DEBUG root [0x00003598] [2019-03-01 13:40:23,616] - Account::~Account(): 7
 DEBUG root [0x00003598] [2019-03-01 13:40:23,617] - Room::~Room(): 3
 DEBUG root [0x00003598] [2019-03-01 13:40:23,617] - Account::~Account(): 2
 DEBUG root [0x00003598] [2019-03-01 13:40:23,617] - Account::~Account(): 4
 DEBUG root [0x00003598] [2019-03-01 13:40:23,619] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x00003598] [2019-03-01 13:40:23,619] - Witness::destroyObjPool(): size 16.
  INFO root [0x00003598] [2019-03-01 13:40:23,664] - Script::uninstall(): is successfully!
 DEBUG root [0x00003598] [2019-03-01 13:40:23,664] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000035f4] [2019-03-01 14:44:01,573] - 
  INFO root [0x000035f4] [2019-03-01 14:44:01,573] - -----------------------------------------------------------------------------------------


  INFO root [0x000035f4] [2019-03-01 14:44:01,581] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x000035f4] [2019-03-01 14:44:01,581] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x000035f4] [2019-03-01 14:44:01,581] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x000035f4] [2019-03-01 14:44:01,584] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:11436 )
  INFO root [0x000035f4] [2019-03-01 14:44:01,584] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:11436, SOMAXCONN=5.
  INFO root [0x000035f4] [2019-03-01 14:44:01,584] - server-configs:
  INFO root [0x000035f4] [2019-03-01 14:44:01,584] - 	gameUpdateHertz : 10
  INFO root [0x000035f4] [2019-03-01 14:44:01,584] - 	defaultViewRadius : 80
  INFO root [0x000035f4] [2019-03-01 14:44:01,584] - 	defaultViewHysteresisArea : 5
  INFO root [0x000035f4] [2019-03-01 14:44:01,584] - 	entryScriptFile : kbemain
  INFO root [0x000035f4] [2019-03-01 14:44:01,584] - 	internalTcpAddr : 192.168.0.148:11436
  INFO root [0x000035f4] [2019-03-01 14:44:01,591] - 	componentID : 8001
  WARN root [0x000035f4] [2019-03-01 14:44:01,594] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  WARN root [0x000035f4] [2019-03-01 14:44:02,208] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20367, errorno=10048
  INFO root [0x000035f4] [2019-03-01 14:44:02,213] - ---- cellapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: E73A667D90DF1EB3CFEA32B1FCE682E5. Config: Debug X86. Built: 17:21:32 Feb 27 2019. AppID: 8001. UID: 28936. PID: 2840 ----
  INFO root [0x000035f4] [2019-03-01 14:44:02,213] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x000035f4] [2019-03-01 14:44:02,214] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000035f4] [2019-03-01 14:44:02,215] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x000035f4] [2019-03-01 14:44:02,393] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x000035f4] [2019-03-01 14:44:02,393] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000035f4] [2019-03-01 14:44:02,482] - loaded entity-script:Account(1).
 DEBUG root [0x000035f4] [2019-03-01 14:44:02,484] - loaded entity-script:Room(3).
  INFO root [0x000035f4] [2019-03-01 14:44:02,484] - TelnetServer server is running on port 50000
  INFO root [0x000035f4] [2019-03-01 14:44:02,873] - ---- cellapp is running ----
 DEBUG root [0x000035f4] [2019-03-01 14:44:02,873] - Components::process(): Request for the process of identity...
  WARN root [0x000035f4] [2019-03-01 14:44:09,027] - EntityApp::checkTickPeriod: tick took 6153% (6.15 seconds)!
  INFO root [0x000035f4] [2019-03-01 14:44:10,074] - Components::findComponents: find logger(1)...
  INFO root [0x000035f4] [2019-03-01 14:44:10,174] - Components::findComponents: found logger, addr:192.168.0.148:11435
  INFO root [0x000035f4] [2019-03-01 14:44:10,174] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x000035f4] [2019-03-01 14:44:10,174] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000035f4] [2019-03-01 14:44:10,175] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000035f4] [2019-03-01 14:44:10,278] - Components::findComponents: found dbmgr, addr:192.168.0.148:11431
  INFO root [0x000035f4] [2019-03-01 14:44:10,278] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x000035f4] [2019-03-01 14:44:10,278] - Components::addComponent[dbmgr], uid=28936, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000035f4] [2019-03-01 14:44:10,278] - Components::findComponents: found dbmgr, addr:192.168.0.148:11431
  WARN root [0x000035f4] [2019-03-01 14:44:11,279] - EntityApp::checkTickPeriod: tick took 1304% (1.30 seconds)!
  WARN root [0x000035f4] [2019-03-01 14:44:11,279] - Forwarding logs to logger[192.168.0.148:11435/0/0/0]...
 ERROR root [0x000035f4] [2019-03-01 14:45:29,794] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x000035f4] [2019-03-01 14:45:29,797] - The following logs sent to logger failed:
  WARN root [0x000035f4] [2019-03-01 14:45:29,797] - ==> [2019-03-01 14:45:29 795] TCPPacketReceiver::processPendingEvents(192.168.0.148:11435): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000035f4] [2019-03-01 14:45:29,798] - ==> [2019-03-01 14:45:29 796] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [0x000035f4] [2019-03-01 14:45:29,839] - TCPPacketReceiver::processPendingEvents(192.168.0.148:11431): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000035f4] [2019-03-01 14:45:29,840] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x000035f4] [2019-03-01 14:45:29,847] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x000035f4] [2019-03-01 14:45:29,849] - Shutdowner::onShutdown: shutting down
 S_DBG root [0x000035f4] [2019-03-01 14:45:29,850] - Avatar::onDestroy: 2.
 S_ERR root [0x000035f4] [2019-03-01 14:45:29,851] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x000035f4] [2019-03-01 14:45:29,853] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
 S_DBG root [0x000035f4] [2019-03-01 14:45:29,854] - Avatar::onDestroy: 4.
 S_ERR root [0x000035f4] [2019-03-01 14:45:29,855] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x000035f4] [2019-03-01 14:45:29,855] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
  INFO root [0x000035f4] [2019-03-01 14:45:29,857] - Spaces::destroySpace: 1.
  INFO root [0x000035f4] [2019-03-01 14:45:29,858] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x000035f4] [2019-03-01 14:45:29,858] - Room::~Room(): 3
 DEBUG root [0x000035f4] [2019-03-01 14:45:29,858] - Account::~Account(): 2
 DEBUG root [0x000035f4] [2019-03-01 14:45:29,858] - Account::~Account(): 4
 DEBUG root [0x000035f4] [2019-03-01 14:45:29,858] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x000035f4] [2019-03-01 14:45:29,859] - Witness::destroyObjPool(): size 16.
  INFO root [0x000035f4] [2019-03-01 14:45:29,878] - Script::uninstall(): is successfully!
 DEBUG root [0x000035f4] [2019-03-01 14:45:29,878] - ThreadPool::destroy(): starting size 2.
  INFO root [0x0000058c] [2019-03-01 15:22:24,698] - 
  INFO root [0x0000058c] [2019-03-01 15:22:24,699] - -----------------------------------------------------------------------------------------


  INFO root [0x0000058c] [2019-03-01 15:22:24,700] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x0000058c] [2019-03-01 15:22:24,701] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x0000058c] [2019-03-01 15:22:24,701] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x0000058c] [2019-03-01 15:22:24,705] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:3498 )
  INFO root [0x0000058c] [2019-03-01 15:22:24,705] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:3498, SOMAXCONN=5.
  INFO root [0x0000058c] [2019-03-01 15:22:24,705] - server-configs:
  INFO root [0x0000058c] [2019-03-01 15:22:24,705] - 	gameUpdateHertz : 10
  INFO root [0x0000058c] [2019-03-01 15:22:24,705] - 	defaultViewRadius : 80
  INFO root [0x0000058c] [2019-03-01 15:22:24,705] - 	defaultViewHysteresisArea : 5
  INFO root [0x0000058c] [2019-03-01 15:22:24,705] - 	entryScriptFile : kbemain
  INFO root [0x0000058c] [2019-03-01 15:22:24,705] - 	internalTcpAddr : 192.168.0.148:3498
  INFO root [0x0000058c] [2019-03-01 15:22:24,706] - 	componentID : 8001
  WARN root [0x0000058c] [2019-03-01 15:22:24,708] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [0x0000058c] [2019-03-01 15:22:26,213] - ---- cellapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: E73A667D90DF1EB3CFEA32B1FCE682E5. Config: Debug X86. Built: 17:21:32 Feb 27 2019. AppID: 8001. UID: 28936. PID: 10348 ----
  INFO root [0x0000058c] [2019-03-01 15:22:26,214] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x0000058c] [2019-03-01 15:22:26,214] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x0000058c] [2019-03-01 15:22:26,214] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x0000058c] [2019-03-01 15:22:26,419] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x0000058c] [2019-03-01 15:22:26,419] - Script::install(): KBExtra is successfully!
 DEBUG root [0x0000058c] [2019-03-01 15:22:26,505] - loaded entity-script:Account(1).
 DEBUG root [0x0000058c] [2019-03-01 15:22:26,506] - loaded entity-script:Room(3).
  INFO root [0x0000058c] [2019-03-01 15:22:26,507] - TelnetServer server is running on port 50000
  INFO root [0x0000058c] [2019-03-01 15:22:26,840] - ---- cellapp is running ----
 DEBUG root [0x0000058c] [2019-03-01 15:22:26,840] - Components::process(): Request for the process of identity...
  WARN root [0x0000058c] [2019-03-01 15:22:33,036] - EntityApp::checkTickPeriod: tick took 6195% (6.20 seconds)!
  INFO root [0x0000058c] [2019-03-01 15:22:34,102] - Components::findComponents: find logger(1)...
  INFO root [0x0000058c] [2019-03-01 15:22:34,120] - Components::findComponents: found logger, addr:192.168.0.148:3493
  INFO root [0x0000058c] [2019-03-01 15:22:34,120] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x0000058c] [2019-03-01 15:22:34,120] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000058c] [2019-03-01 15:22:34,122] - Components::findComponents: find dbmgr(2)...
  INFO root [0x0000058c] [2019-03-01 15:22:34,226] - Components::findComponents: found dbmgr, addr:192.168.0.148:3496
  INFO root [0x0000058c] [2019-03-01 15:22:34,227] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x0000058c] [2019-03-01 15:22:34,228] - Components::addComponent[dbmgr], uid=28936, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000058c] [2019-03-01 15:22:34,228] - Components::findComponents: found dbmgr, addr:192.168.0.148:3496
  WARN root [0x0000058c] [2019-03-01 15:22:35,228] - Forwarding logs to logger[192.168.0.148:3493/0/0/0]...
 ERROR root [0x0000058c] [2019-03-01 15:23:45,817] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x0000058c] [2019-03-01 15:23:45,822] - The following logs sent to logger failed:
  WARN root [0x0000058c] [2019-03-01 15:23:45,823] - ==> [2019-03-01 15:23:45 816] TCPPacketReceiver::processPendingEvents(192.168.0.148:3493): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000058c] [2019-03-01 15:23:45,824] - ==> [2019-03-01 15:23:45 818] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [0x0000058c] [2019-03-01 15:23:45,860] - TCPPacketReceiver::processPendingEvents(192.168.0.148:3496): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000058c] [2019-03-01 15:23:45,861] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x0000058c] [2019-03-01 15:23:45,864] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x0000058c] [2019-03-01 15:23:45,869] - Shutdowner::onShutdown: shutting down
 S_DBG root [0x0000058c] [2019-03-01 15:23:45,870] - Avatar::onDestroy: 2.
 S_ERR root [0x0000058c] [2019-03-01 15:23:45,871] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x0000058c] [2019-03-01 15:23:45,874] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
 S_DBG root [0x0000058c] [2019-03-01 15:23:45,877] - Avatar::onDestroy: 4.
 S_ERR root [0x0000058c] [2019-03-01 15:23:45,877] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x0000058c] [2019-03-01 15:23:45,879] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
  INFO root [0x0000058c] [2019-03-01 15:23:45,880] - Spaces::destroySpace: 1.
  INFO root [0x0000058c] [2019-03-01 15:23:45,880] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x0000058c] [2019-03-01 15:23:45,881] - Room::~Room(): 3
 DEBUG root [0x0000058c] [2019-03-01 15:23:45,881] - Account::~Account(): 2
 DEBUG root [0x0000058c] [2019-03-01 15:23:45,881] - Account::~Account(): 4
 DEBUG root [0x0000058c] [2019-03-01 15:23:45,881] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x0000058c] [2019-03-01 15:23:45,881] - Witness::destroyObjPool(): size 16.
  INFO root [0x0000058c] [2019-03-01 15:23:45,900] - Script::uninstall(): is successfully!
 DEBUG root [0x0000058c] [2019-03-01 15:23:45,901] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003330] [2019-03-01 15:43:02,936] - 
  INFO root [0x00003330] [2019-03-01 15:43:02,936] - -----------------------------------------------------------------------------------------


  INFO root [0x00003330] [2019-03-01 15:43:02,938] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x00003330] [2019-03-01 15:43:02,938] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x00003330] [2019-03-01 15:43:02,942] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x00003330] [2019-03-01 15:43:02,960] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:6678 )
  INFO root [0x00003330] [2019-03-01 15:43:02,960] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:6678, SOMAXCONN=5.
  INFO root [0x00003330] [2019-03-01 15:43:02,961] - server-configs:
  INFO root [0x00003330] [2019-03-01 15:43:02,961] - 	gameUpdateHertz : 10
  INFO root [0x00003330] [2019-03-01 15:43:02,961] - 	defaultViewRadius : 80
  INFO root [0x00003330] [2019-03-01 15:43:02,961] - 	defaultViewHysteresisArea : 5
  INFO root [0x00003330] [2019-03-01 15:43:02,962] - 	entryScriptFile : kbemain
  INFO root [0x00003330] [2019-03-01 15:43:02,962] - 	internalTcpAddr : 192.168.0.148:6678
  INFO root [0x00003330] [2019-03-01 15:43:02,962] - 	componentID : 8001
  WARN root [0x00003330] [2019-03-01 15:43:02,967] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [0x00003330] [2019-03-01 15:43:04,471] - ---- cellapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: E73A667D90DF1EB3CFEA32B1FCE682E5. Config: Debug X86. Built: 17:21:32 Feb 27 2019. AppID: 8001. UID: 28936. PID: 13628 ----
  INFO root [0x00003330] [2019-03-01 15:43:04,472] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x00003330] [2019-03-01 15:43:04,472] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003330] [2019-03-01 15:43:04,472] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00003330] [2019-03-01 15:43:04,666] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00003330] [2019-03-01 15:43:04,666] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003330] [2019-03-01 15:43:04,751] - loaded entity-script:Account(1).
 DEBUG root [0x00003330] [2019-03-01 15:43:04,752] - loaded entity-script:Room(3).
  INFO root [0x00003330] [2019-03-01 15:43:04,753] - TelnetServer server is running on port 50000
  INFO root [0x00003330] [2019-03-01 15:43:05,092] - ---- cellapp is running ----
 DEBUG root [0x00003330] [2019-03-01 15:43:05,092] - Components::process(): Request for the process of identity...
  WARN root [0x00003330] [2019-03-01 15:43:11,266] - EntityApp::checkTickPeriod: tick took 6174% (6.17 seconds)!
  INFO root [0x00003330] [2019-03-01 15:43:12,293] - Components::findComponents: find logger(1)...
  INFO root [0x00003330] [2019-03-01 15:43:12,350] - Components::findComponents: found logger, addr:192.168.0.148:6676
  INFO root [0x00003330] [2019-03-01 15:43:12,350] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00003330] [2019-03-01 15:43:12,350] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003330] [2019-03-01 15:43:12,352] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003330] [2019-03-01 15:43:12,455] - Components::findComponents: found dbmgr, addr:192.168.0.148:6679
  INFO root [0x00003330] [2019-03-01 15:43:12,455] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00003330] [2019-03-01 15:43:12,456] - Components::addComponent[dbmgr], uid=28936, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003330] [2019-03-01 15:43:12,463] - Components::findComponents: found dbmgr, addr:192.168.0.148:6679
  WARN root [0x00003330] [2019-03-01 15:43:13,464] - EntityApp::checkTickPeriod: tick took 1271% (1.27 seconds)!
  WARN root [0x00003330] [2019-03-01 15:43:13,464] - Forwarding logs to logger[192.168.0.148:6676/0/0/0]...
 ERROR root [0x00003330] [2019-03-01 15:44:32,833] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00003330] [2019-03-01 15:44:32,837] - The following logs sent to logger failed:
  WARN root [0x00003330] [2019-03-01 15:44:32,838] - ==> [2019-03-01 15:44:32 832] TCPPacketReceiver::processPendingEvents(192.168.0.148:6676): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003330] [2019-03-01 15:44:32,838] - ==> [2019-03-01 15:44:32 834] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [0x00003330] [2019-03-01 15:44:32,870] - TCPPacketReceiver::processPendingEvents(192.168.0.148:6679): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003330] [2019-03-01 15:44:32,872] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00003330] [2019-03-01 15:44:32,877] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00003330] [2019-03-01 15:44:32,879] - Shutdowner::onShutdown: shutting down
 S_DBG root [0x00003330] [2019-03-01 15:44:32,881] - Avatar::onDestroy: 2.
 S_ERR root [0x00003330] [2019-03-01 15:44:32,882] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x00003330] [2019-03-01 15:44:32,884] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
 S_DBG root [0x00003330] [2019-03-01 15:44:32,886] - Avatar::onDestroy: 4.
 S_ERR root [0x00003330] [2019-03-01 15:44:32,887] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x00003330] [2019-03-01 15:44:32,888] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
  INFO root [0x00003330] [2019-03-01 15:44:32,889] - Spaces::destroySpace: 1.
  INFO root [0x00003330] [2019-03-01 15:44:32,890] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00003330] [2019-03-01 15:44:32,890] - Room::~Room(): 3
 DEBUG root [0x00003330] [2019-03-01 15:44:32,891] - Account::~Account(): 2
 DEBUG root [0x00003330] [2019-03-01 15:44:32,891] - Account::~Account(): 4
 DEBUG root [0x00003330] [2019-03-01 15:44:32,892] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x00003330] [2019-03-01 15:44:32,893] - Witness::destroyObjPool(): size 16.
  INFO root [0x00003330] [2019-03-01 15:44:32,910] - Script::uninstall(): is successfully!
 DEBUG root [0x00003330] [2019-03-01 15:44:32,910] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003ad4] [2019-03-01 15:47:39,200] - 
  INFO root [0x00003ad4] [2019-03-01 15:47:39,201] - -----------------------------------------------------------------------------------------


  INFO root [0x00003ad4] [2019-03-01 15:47:39,203] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x00003ad4] [2019-03-01 15:47:39,203] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x00003ad4] [2019-03-01 15:47:39,204] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x00003ad4] [2019-03-01 15:47:39,208] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:7417 )
  INFO root [0x00003ad4] [2019-03-01 15:47:39,209] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:7417, SOMAXCONN=5.
  INFO root [0x00003ad4] [2019-03-01 15:47:39,209] - server-configs:
  INFO root [0x00003ad4] [2019-03-01 15:47:39,209] - 	gameUpdateHertz : 10
  INFO root [0x00003ad4] [2019-03-01 15:47:39,209] - 	defaultViewRadius : 80
  INFO root [0x00003ad4] [2019-03-01 15:47:39,209] - 	defaultViewHysteresisArea : 5
  INFO root [0x00003ad4] [2019-03-01 15:47:39,210] - 	entryScriptFile : kbemain
  INFO root [0x00003ad4] [2019-03-01 15:47:39,210] - 	internalTcpAddr : 192.168.0.148:7417
  INFO root [0x00003ad4] [2019-03-01 15:47:39,210] - 	componentID : 8001
  WARN root [0x00003ad4] [2019-03-01 15:47:39,213] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [0x00003ad4] [2019-03-01 15:47:40,722] - ---- cellapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: E73A667D90DF1EB3CFEA32B1FCE682E5. Config: Debug X86. Built: 17:21:32 Feb 27 2019. AppID: 8001. UID: 28936. PID: 16220 ----
  INFO root [0x00003ad4] [2019-03-01 15:47:40,722] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x00003ad4] [2019-03-01 15:47:40,722] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003ad4] [2019-03-01 15:47:40,722] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00003ad4] [2019-03-01 15:47:40,913] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00003ad4] [2019-03-01 15:47:40,913] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003ad4] [2019-03-01 15:47:41,022] - loaded entity-script:Account(1).
 DEBUG root [0x00003ad4] [2019-03-01 15:47:41,024] - loaded entity-script:Room(3).
  INFO root [0x00003ad4] [2019-03-01 15:47:41,025] - TelnetServer server is running on port 50000
  INFO root [0x00003ad4] [2019-03-01 15:47:41,468] - ---- cellapp is running ----
 DEBUG root [0x00003ad4] [2019-03-01 15:47:41,469] - Components::process(): Request for the process of identity...
  WARN root [0x00003ad4] [2019-03-01 15:47:47,674] - EntityApp::checkTickPeriod: tick took 6205% (6.20 seconds)!
  INFO root [0x00003ad4] [2019-03-01 15:47:48,706] - Components::findComponents: find logger(1)...
  INFO root [0x00003ad4] [2019-03-01 15:47:48,764] - Components::findComponents: found logger, addr:192.168.0.148:7412
  INFO root [0x00003ad4] [2019-03-01 15:47:48,765] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00003ad4] [2019-03-01 15:47:48,767] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003ad4] [2019-03-01 15:47:48,771] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003ad4] [2019-03-01 15:47:48,877] - Components::findComponents: found dbmgr, addr:192.168.0.148:7414
  INFO root [0x00003ad4] [2019-03-01 15:47:48,878] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00003ad4] [2019-03-01 15:47:48,879] - Components::addComponent[dbmgr], uid=28936, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003ad4] [2019-03-01 15:47:48,880] - Components::findComponents: found dbmgr, addr:192.168.0.148:7414
  WARN root [0x00003ad4] [2019-03-01 15:47:49,881] - Forwarding logs to logger[192.168.0.148:7412/0/0/0]...
 ERROR root [0x00003ad4] [2019-03-01 16:10:37,752] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00003ad4] [2019-03-01 16:10:37,756] - The following logs sent to logger failed:
  WARN root [0x00003ad4] [2019-03-01 16:10:37,756] - ==> [2019-03-01 16:10:37 752] TCPPacketReceiver::processPendingEvents(192.168.0.148:7412): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003ad4] [2019-03-01 16:10:37,756] - ==> [2019-03-01 16:10:37 754] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [0x00003ad4] [2019-03-01 16:10:37,797] - TCPPacketReceiver::processPendingEvents(192.168.0.148:7414): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003ad4] [2019-03-01 16:10:37,798] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00003ad4] [2019-03-01 16:10:37,804] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00003ad4] [2019-03-01 16:10:37,807] - Shutdowner::onShutdown: shutting down
 S_DBG root [0x00003ad4] [2019-03-01 16:10:37,809] - Avatar::onDestroy: 10.
 S_ERR root [0x00003ad4] [2019-03-01 16:10:37,811] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x00003ad4] [2019-03-01 16:10:37,814] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
 S_DBG root [0x00003ad4] [2019-03-01 16:10:37,816] - Avatar::onDestroy: 2.
 S_ERR root [0x00003ad4] [2019-03-01 16:10:37,817] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x00003ad4] [2019-03-01 16:10:37,818] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
 S_DBG root [0x00003ad4] [2019-03-01 16:10:37,820] - Avatar::onDestroy: 4.
 S_ERR root [0x00003ad4] [2019-03-01 16:10:37,820] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x00003ad4] [2019-03-01 16:10:37,821] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
  INFO root [0x00003ad4] [2019-03-01 16:10:37,824] - Spaces::destroySpace: 1.
 S_DBG root [0x00003ad4] [2019-03-01 16:10:37,825] - Avatar::onDestroy: 5.
 S_ERR root [0x00003ad4] [2019-03-01 16:10:37,825] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x00003ad4] [2019-03-01 16:10:37,826] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
 S_DBG root [0x00003ad4] [2019-03-01 16:10:37,828] - Avatar::onDestroy: 7.
 S_ERR root [0x00003ad4] [2019-03-01 16:10:37,828] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x00003ad4] [2019-03-01 16:10:37,829] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
  INFO root [0x00003ad4] [2019-03-01 16:10:37,830] - Spaces::destroySpace: 2.
 S_DBG root [0x00003ad4] [2019-03-01 16:10:37,831] - Avatar::onDestroy: 8.
 S_ERR root [0x00003ad4] [2019-03-01 16:10:37,831] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x00003ad4] [2019-03-01 16:10:37,832] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
  INFO root [0x00003ad4] [2019-03-01 16:10:37,834] - Spaces::destroySpace: 3.
  INFO root [0x00003ad4] [2019-03-01 16:10:37,834] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00003ad4] [2019-03-01 16:10:37,835] - Account::~Account(): 10
 DEBUG root [0x00003ad4] [2019-03-01 16:10:37,835] - Room::~Room(): 9
 DEBUG root [0x00003ad4] [2019-03-01 16:10:37,836] - Account::~Account(): 8
 DEBUG root [0x00003ad4] [2019-03-01 16:10:37,837] - Room::~Room(): 6
 DEBUG root [0x00003ad4] [2019-03-01 16:10:37,837] - Account::~Account(): 5
 DEBUG root [0x00003ad4] [2019-03-01 16:10:37,837] - Account::~Account(): 7
 DEBUG root [0x00003ad4] [2019-03-01 16:10:37,838] - Room::~Room(): 3
 DEBUG root [0x00003ad4] [2019-03-01 16:10:37,838] - Account::~Account(): 2
 DEBUG root [0x00003ad4] [2019-03-01 16:10:37,838] - Account::~Account(): 4
 DEBUG root [0x00003ad4] [2019-03-01 16:10:37,839] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x00003ad4] [2019-03-01 16:10:37,839] - Witness::destroyObjPool(): size 16.
  INFO root [0x00003ad4] [2019-03-01 16:10:37,864] - Script::uninstall(): is successfully!
 DEBUG root [0x00003ad4] [2019-03-01 16:10:37,865] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000039a0] [2019-03-01 16:10:40,555] - 
  INFO root [0x000039a0] [2019-03-01 16:10:40,557] - -----------------------------------------------------------------------------------------


  INFO root [0x000039a0] [2019-03-01 16:10:40,560] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x000039a0] [2019-03-01 16:10:40,561] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x000039a0] [2019-03-01 16:10:40,562] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x000039a0] [2019-03-01 16:10:40,569] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:10987 )
  INFO root [0x000039a0] [2019-03-01 16:10:40,569] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:10987, SOMAXCONN=5.
  INFO root [0x000039a0] [2019-03-01 16:10:40,569] - server-configs:
  INFO root [0x000039a0] [2019-03-01 16:10:40,569] - 	gameUpdateHertz : 10
  INFO root [0x000039a0] [2019-03-01 16:10:40,570] - 	defaultViewRadius : 80
  INFO root [0x000039a0] [2019-03-01 16:10:40,570] - 	defaultViewHysteresisArea : 5
  INFO root [0x000039a0] [2019-03-01 16:10:40,570] - 	entryScriptFile : kbemain
  INFO root [0x000039a0] [2019-03-01 16:10:40,570] - 	internalTcpAddr : 192.168.0.148:10987
  INFO root [0x000039a0] [2019-03-01 16:10:40,570] - 	componentID : 8001
  WARN root [0x000039a0] [2019-03-01 16:10:40,575] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  WARN root [0x000039a0] [2019-03-01 16:10:40,917] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20237, errorno=10048
  INFO root [0x000039a0] [2019-03-01 16:10:40,920] - ---- cellapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: E73A667D90DF1EB3CFEA32B1FCE682E5. Config: Debug X86. Built: 17:21:32 Feb 27 2019. AppID: 8001. UID: 28936. PID: 14432 ----
  INFO root [0x000039a0] [2019-03-01 16:10:40,920] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x000039a0] [2019-03-01 16:10:40,921] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000039a0] [2019-03-01 16:10:40,921] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x000039a0] [2019-03-01 16:10:41,097] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x000039a0] [2019-03-01 16:10:41,097] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000039a0] [2019-03-01 16:10:41,185] - loaded entity-script:Account(1).
 DEBUG root [0x000039a0] [2019-03-01 16:10:41,186] - loaded entity-script:Room(3).
  INFO root [0x000039a0] [2019-03-01 16:10:41,186] - TelnetServer server is running on port 50000
  INFO root [0x000039a0] [2019-03-01 16:10:41,546] - ---- cellapp is running ----
 DEBUG root [0x000039a0] [2019-03-01 16:10:41,546] - Components::process(): Request for the process of identity...
  WARN root [0x000039a0] [2019-03-01 16:10:47,703] - EntityApp::checkTickPeriod: tick took 6157% (6.16 seconds)!
  INFO root [0x000039a0] [2019-03-01 16:10:48,747] - Components::findComponents: find logger(1)...
  INFO root [0x000039a0] [2019-03-01 16:10:48,764] - Components::findComponents: found logger, addr:192.168.0.148:10989
  INFO root [0x000039a0] [2019-03-01 16:10:48,765] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x000039a0] [2019-03-01 16:10:48,765] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000039a0] [2019-03-01 16:10:48,767] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000039a0] [2019-03-01 16:10:48,871] - Components::findComponents: found dbmgr, addr:192.168.0.148:10985
  INFO root [0x000039a0] [2019-03-01 16:10:48,872] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x000039a0] [2019-03-01 16:10:48,872] - Components::addComponent[dbmgr], uid=28936, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000039a0] [2019-03-01 16:10:48,874] - Components::findComponents: found dbmgr, addr:192.168.0.148:10985
  WARN root [0x000039a0] [2019-03-01 16:10:49,874] - EntityApp::checkTickPeriod: tick took 1228% (1.23 seconds)!
  WARN root [0x000039a0] [2019-03-01 16:10:49,876] - Forwarding logs to logger[192.168.0.148:10989/0/0/0]...
 ERROR root [0x000039a0] [2019-03-01 16:29:18,822] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x000039a0] [2019-03-01 16:29:18,828] - The following logs sent to logger failed:
  WARN root [0x000039a0] [2019-03-01 16:29:18,828] - ==> [2019-03-01 16:29:18 821] TCPPacketReceiver::processPendingEvents(192.168.0.148:10989): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000039a0] [2019-03-01 16:29:18,828] - ==> [2019-03-01 16:29:18 824] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [0x000039a0] [2019-03-01 16:29:18,871] - TCPPacketReceiver::processPendingEvents(192.168.0.148:10985): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000039a0] [2019-03-01 16:29:18,872] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x000039a0] [2019-03-01 16:29:18,879] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x000039a0] [2019-03-01 16:29:18,884] - Shutdowner::onShutdown: shutting down
 S_DBG root [0x000039a0] [2019-03-01 16:29:18,886] - Avatar::onDestroy: 2002.
 S_ERR root [0x000039a0] [2019-03-01 16:29:18,887] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x000039a0] [2019-03-01 16:29:18,893] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
 S_DBG root [0x000039a0] [2019-03-01 16:29:18,895] - Avatar::onDestroy: 2004.
 S_ERR root [0x000039a0] [2019-03-01 16:29:18,896] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x000039a0] [2019-03-01 16:29:18,897] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
  INFO root [0x000039a0] [2019-03-01 16:29:18,901] - Spaces::destroySpace: 1.
 S_DBG root [0x000039a0] [2019-03-01 16:29:18,902] - Avatar::onDestroy: 2005.
 S_ERR root [0x000039a0] [2019-03-01 16:29:18,903] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x000039a0] [2019-03-01 16:29:18,904] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
 S_DBG root [0x000039a0] [2019-03-01 16:29:18,906] - Avatar::onDestroy: 2007.
 S_ERR root [0x000039a0] [2019-03-01 16:29:18,906] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x000039a0] [2019-03-01 16:29:18,907] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
  INFO root [0x000039a0] [2019-03-01 16:29:18,909] - Spaces::destroySpace: 2.
  INFO root [0x000039a0] [2019-03-01 16:29:18,909] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x000039a0] [2019-03-01 16:29:18,910] - Room::~Room(): 2006
 DEBUG root [0x000039a0] [2019-03-01 16:29:18,910] - Account::~Account(): 2005
 DEBUG root [0x000039a0] [2019-03-01 16:29:18,910] - Account::~Account(): 2007
 DEBUG root [0x000039a0] [2019-03-01 16:29:18,911] - Room::~Room(): 2003
 DEBUG root [0x000039a0] [2019-03-01 16:29:18,911] - Account::~Account(): 2002
 DEBUG root [0x000039a0] [2019-03-01 16:29:18,911] - Account::~Account(): 2004
 DEBUG root [0x000039a0] [2019-03-01 16:29:18,912] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x000039a0] [2019-03-01 16:29:18,912] - Witness::destroyObjPool(): size 16.
  INFO root [0x000039a0] [2019-03-01 16:29:18,954] - Script::uninstall(): is successfully!
 DEBUG root [0x000039a0] [2019-03-01 16:29:18,954] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003228] [2019-03-01 16:29:33,510] - 
  INFO root [0x00003228] [2019-03-01 16:29:33,512] - -----------------------------------------------------------------------------------------


  INFO root [0x00003228] [2019-03-01 16:29:33,516] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x00003228] [2019-03-01 16:29:33,517] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x00003228] [2019-03-01 16:29:33,518] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x00003228] [2019-03-01 16:29:33,529] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:14039 )
  INFO root [0x00003228] [2019-03-01 16:29:33,530] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:14039, SOMAXCONN=5.
  INFO root [0x00003228] [2019-03-01 16:29:33,530] - server-configs:
  INFO root [0x00003228] [2019-03-01 16:29:33,530] - 	gameUpdateHertz : 10
  INFO root [0x00003228] [2019-03-01 16:29:33,530] - 	defaultViewRadius : 80
  INFO root [0x00003228] [2019-03-01 16:29:33,530] - 	defaultViewHysteresisArea : 5
  INFO root [0x00003228] [2019-03-01 16:29:33,531] - 	entryScriptFile : kbemain
  INFO root [0x00003228] [2019-03-01 16:29:33,531] - 	internalTcpAddr : 192.168.0.148:14039
  INFO root [0x00003228] [2019-03-01 16:29:33,531] - 	componentID : 8001
  WARN root [0x00003228] [2019-03-01 16:29:33,538] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [0x00003228] [2019-03-01 16:29:35,048] - ---- cellapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: E73A667D90DF1EB3CFEA32B1FCE682E5. Config: Debug X86. Built: 17:21:32 Feb 27 2019. AppID: 8001. UID: 28936. PID: 3516 ----
  INFO root [0x00003228] [2019-03-01 16:29:35,048] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x00003228] [2019-03-01 16:29:35,049] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003228] [2019-03-01 16:29:35,050] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00003228] [2019-03-01 16:29:35,328] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00003228] [2019-03-01 16:29:35,329] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003228] [2019-03-01 16:29:35,547] - loaded entity-script:Account(1).
 DEBUG root [0x00003228] [2019-03-01 16:29:35,550] - loaded entity-script:Room(3).
  INFO root [0x00003228] [2019-03-01 16:29:35,551] - TelnetServer server is running on port 50000
  INFO root [0x00003228] [2019-03-01 16:29:36,525] - ---- cellapp is running ----
 DEBUG root [0x00003228] [2019-03-01 16:29:36,525] - Components::process(): Request for the process of identity...
  WARN root [0x00003228] [2019-03-01 16:29:42,700] - EntityApp::checkTickPeriod: tick took 6174% (6.17 seconds)!
  INFO root [0x00003228] [2019-03-01 16:29:43,724] - Components::findComponents: find logger(1)...
  INFO root [0x00003228] [2019-03-01 16:29:43,809] - Components::findComponents: found logger, addr:192.168.0.148:14041
  INFO root [0x00003228] [2019-03-01 16:29:43,809] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00003228] [2019-03-01 16:29:43,809] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003228] [2019-03-01 16:29:43,810] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003228] [2019-03-01 16:29:43,915] - Components::findComponents: found dbmgr, addr:192.168.0.148:14032
  INFO root [0x00003228] [2019-03-01 16:29:43,915] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00003228] [2019-03-01 16:29:43,916] - Components::addComponent[dbmgr], uid=28936, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003228] [2019-03-01 16:29:43,924] - Components::findComponents: found dbmgr, addr:192.168.0.148:14032
  WARN root [0x00003228] [2019-03-01 16:29:44,925] - Forwarding logs to logger[192.168.0.148:14041/0/0/0]...
 ERROR root [0x00003228] [2019-03-01 16:36:46,647] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00003228] [2019-03-01 16:36:46,650] - The following logs sent to logger failed:
  WARN root [0x00003228] [2019-03-01 16:36:46,651] - ==> [2019-03-01 16:36:46 647] TCPPacketReceiver::processPendingEvents(192.168.0.148:14041): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003228] [2019-03-01 16:36:46,651] - ==> [2019-03-01 16:36:46 648] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [0x00003228] [2019-03-01 16:36:46,701] - TCPPacketReceiver::processPendingEvents(192.168.0.148:14032): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003228] [2019-03-01 16:36:46,701] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00003228] [2019-03-01 16:36:46,707] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00003228] [2019-03-01 16:36:46,709] - Shutdowner::onShutdown: shutting down
 S_DBG root [0x00003228] [2019-03-01 16:36:46,711] - Avatar::onDestroy: 2.
 S_ERR root [0x00003228] [2019-03-01 16:36:46,712] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x00003228] [2019-03-01 16:36:46,715] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
 S_DBG root [0x00003228] [2019-03-01 16:36:46,718] - Avatar::onDestroy: 4.
 S_ERR root [0x00003228] [2019-03-01 16:36:46,719] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x00003228] [2019-03-01 16:36:46,722] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
  INFO root [0x00003228] [2019-03-01 16:36:46,723] - Spaces::destroySpace: 1.
 S_DBG root [0x00003228] [2019-03-01 16:36:46,724] - Avatar::onDestroy: 5.
 S_ERR root [0x00003228] [2019-03-01 16:36:46,724] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x00003228] [2019-03-01 16:36:46,727] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
 S_DBG root [0x00003228] [2019-03-01 16:36:46,729] - Avatar::onDestroy: 7.
 S_ERR root [0x00003228] [2019-03-01 16:36:46,729] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x00003228] [2019-03-01 16:36:46,730] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
  INFO root [0x00003228] [2019-03-01 16:36:46,732] - Spaces::destroySpace: 2.
  INFO root [0x00003228] [2019-03-01 16:36:46,732] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00003228] [2019-03-01 16:36:46,733] - Room::~Room(): 6
 DEBUG root [0x00003228] [2019-03-01 16:36:46,733] - Account::~Account(): 5
 DEBUG root [0x00003228] [2019-03-01 16:36:46,733] - Account::~Account(): 7
 DEBUG root [0x00003228] [2019-03-01 16:36:46,733] - Room::~Room(): 3
 DEBUG root [0x00003228] [2019-03-01 16:36:46,733] - Account::~Account(): 2
 DEBUG root [0x00003228] [2019-03-01 16:36:46,733] - Account::~Account(): 4
 DEBUG root [0x00003228] [2019-03-01 16:36:46,734] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x00003228] [2019-03-01 16:36:46,734] - Witness::destroyObjPool(): size 16.
  INFO root [0x00003228] [2019-03-01 16:36:46,751] - Script::uninstall(): is successfully!
 DEBUG root [0x00003228] [2019-03-01 16:36:46,751] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00001e40] [2019-03-01 16:38:50,815] - 
  INFO root [0x00001e40] [2019-03-01 16:38:50,817] - -----------------------------------------------------------------------------------------


  INFO root [0x00001e40] [2019-03-01 16:38:50,818] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x00001e40] [2019-03-01 16:38:50,819] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x00001e40] [2019-03-01 16:38:50,819] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x00001e40] [2019-03-01 16:38:50,824] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:7131 )
  INFO root [0x00001e40] [2019-03-01 16:38:50,825] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:7131, SOMAXCONN=5.
  INFO root [0x00001e40] [2019-03-01 16:38:50,825] - server-configs:
  INFO root [0x00001e40] [2019-03-01 16:38:50,825] - 	gameUpdateHertz : 10
  INFO root [0x00001e40] [2019-03-01 16:38:50,826] - 	defaultViewRadius : 80
  INFO root [0x00001e40] [2019-03-01 16:38:50,826] - 	defaultViewHysteresisArea : 5
  INFO root [0x00001e40] [2019-03-01 16:38:50,826] - 	entryScriptFile : kbemain
  INFO root [0x00001e40] [2019-03-01 16:38:50,826] - 	internalTcpAddr : 192.168.0.148:7131
  INFO root [0x00001e40] [2019-03-01 16:38:50,826] - 	componentID : 8001
  WARN root [0x00001e40] [2019-03-01 16:38:50,830] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [0x00001e40] [2019-03-01 16:38:52,336] - ---- cellapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: E73A667D90DF1EB3CFEA32B1FCE682E5. Config: Debug X86. Built: 17:21:32 Feb 27 2019. AppID: 8001. UID: 28936. PID: 14412 ----
  INFO root [0x00001e40] [2019-03-01 16:38:52,336] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x00001e40] [2019-03-01 16:38:52,336] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001e40] [2019-03-01 16:38:52,337] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00001e40] [2019-03-01 16:38:52,507] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00001e40] [2019-03-01 16:38:52,507] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00001e40] [2019-03-01 16:38:52,601] - loaded entity-script:Account(1).
 DEBUG root [0x00001e40] [2019-03-01 16:38:52,603] - loaded entity-script:Room(3).
  INFO root [0x00001e40] [2019-03-01 16:38:52,603] - TelnetServer server is running on port 50000
  INFO root [0x00001e40] [2019-03-01 16:38:52,954] - ---- cellapp is running ----
 DEBUG root [0x00001e40] [2019-03-01 16:38:52,954] - Components::process(): Request for the process of identity...
  WARN root [0x00001e40] [2019-03-01 16:38:59,088] - EntityApp::checkTickPeriod: tick took 6134% (6.13 seconds)!
  INFO root [0x00001e40] [2019-03-01 16:39:00,155] - Components::findComponents: find logger(1)...
  INFO root [0x00001e40] [2019-03-01 16:39:00,201] - Components::findComponents: found logger, addr:192.168.0.148:7134
  INFO root [0x00001e40] [2019-03-01 16:39:00,202] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00001e40] [2019-03-01 16:39:00,202] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001e40] [2019-03-01 16:39:00,204] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00001e40] [2019-03-01 16:39:00,308] - Components::findComponents: found dbmgr, addr:192.168.0.148:7127
  INFO root [0x00001e40] [2019-03-01 16:39:00,308] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00001e40] [2019-03-01 16:39:00,309] - Components::addComponent[dbmgr], uid=28936, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001e40] [2019-03-01 16:39:00,309] - Components::findComponents: found dbmgr, addr:192.168.0.148:7127
  WARN root [0x00001e40] [2019-03-01 16:39:01,309] - EntityApp::checkTickPeriod: tick took 1254% (1.25 seconds)!
  WARN root [0x00001e40] [2019-03-01 16:39:01,310] - Forwarding logs to logger[192.168.0.148:7134/0/0/0]...
 ERROR root [0x00001e40] [2019-03-01 16:46:14,656] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00001e40] [2019-03-01 16:46:14,665] - The following logs sent to logger failed:
  WARN root [0x00001e40] [2019-03-01 16:46:14,665] - ==> [2019-03-01 16:46:14 656] TCPPacketReceiver::processPendingEvents(192.168.0.148:7134): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001e40] [2019-03-01 16:46:14,666] - ==> [2019-03-01 16:46:14 658] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [0x00001e40] [2019-03-01 16:46:14,697] - TCPPacketReceiver::processPendingEvents(192.168.0.148:7127): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001e40] [2019-03-01 16:46:14,698] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00001e40] [2019-03-01 16:46:14,703] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00001e40] [2019-03-01 16:46:14,705] - Shutdowner::onShutdown: shutting down
 S_DBG root [0x00001e40] [2019-03-01 16:46:14,706] - Avatar::onDestroy: 2.
 S_ERR root [0x00001e40] [2019-03-01 16:46:14,708] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x00001e40] [2019-03-01 16:46:14,711] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
 S_DBG root [0x00001e40] [2019-03-01 16:46:14,714] - Avatar::onDestroy: 4.
 S_ERR root [0x00001e40] [2019-03-01 16:46:14,714] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x00001e40] [2019-03-01 16:46:14,715] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
  INFO root [0x00001e40] [2019-03-01 16:46:14,716] - Spaces::destroySpace: 1.
 S_DBG root [0x00001e40] [2019-03-01 16:46:14,717] - Avatar::onDestroy: 5.
 S_ERR root [0x00001e40] [2019-03-01 16:46:14,718] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x00001e40] [2019-03-01 16:46:14,718] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
 S_DBG root [0x00001e40] [2019-03-01 16:46:14,719] - Avatar::onDestroy: 7.
 S_ERR root [0x00001e40] [2019-03-01 16:46:14,720] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x00001e40] [2019-03-01 16:46:14,720] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
  INFO root [0x00001e40] [2019-03-01 16:46:14,723] - Spaces::destroySpace: 2.
  INFO root [0x00001e40] [2019-03-01 16:46:14,723] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00001e40] [2019-03-01 16:46:14,724] - Room::~Room(): 6
 DEBUG root [0x00001e40] [2019-03-01 16:46:14,724] - Account::~Account(): 5
 DEBUG root [0x00001e40] [2019-03-01 16:46:14,724] - Account::~Account(): 7
 DEBUG root [0x00001e40] [2019-03-01 16:46:14,725] - Room::~Room(): 3
 DEBUG root [0x00001e40] [2019-03-01 16:46:14,725] - Account::~Account(): 2
 DEBUG root [0x00001e40] [2019-03-01 16:46:14,725] - Account::~Account(): 4
 DEBUG root [0x00001e40] [2019-03-01 16:46:14,726] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x00001e40] [2019-03-01 16:46:14,726] - Witness::destroyObjPool(): size 16.
  INFO root [0x00001e40] [2019-03-01 16:46:14,749] - Script::uninstall(): is successfully!
 DEBUG root [0x00001e40] [2019-03-01 16:46:14,749] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003650] [2019-03-01 16:46:46,102] - 
  INFO root [0x00003650] [2019-03-01 16:46:46,102] - -----------------------------------------------------------------------------------------


  INFO root [0x00003650] [2019-03-01 16:46:46,103] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x00003650] [2019-03-01 16:46:46,103] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x00003650] [2019-03-01 16:46:46,104] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x00003650] [2019-03-01 16:46:46,107] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:8381 )
  INFO root [0x00003650] [2019-03-01 16:46:46,108] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:8381, SOMAXCONN=5.
  INFO root [0x00003650] [2019-03-01 16:46:46,108] - server-configs:
  INFO root [0x00003650] [2019-03-01 16:46:46,108] - 	gameUpdateHertz : 10
  INFO root [0x00003650] [2019-03-01 16:46:46,108] - 	defaultViewRadius : 80
  INFO root [0x00003650] [2019-03-01 16:46:46,108] - 	defaultViewHysteresisArea : 5
  INFO root [0x00003650] [2019-03-01 16:46:46,108] - 	entryScriptFile : kbemain
  INFO root [0x00003650] [2019-03-01 16:46:46,109] - 	internalTcpAddr : 192.168.0.148:8381
  INFO root [0x00003650] [2019-03-01 16:46:46,109] - 	componentID : 8001
  WARN root [0x00003650] [2019-03-01 16:46:46,113] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [0x00003650] [2019-03-01 16:46:47,617] - ---- cellapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: E73A667D90DF1EB3CFEA32B1FCE682E5. Config: Debug X86. Built: 17:21:32 Feb 27 2019. AppID: 8001. UID: 28936. PID: 13604 ----
  INFO root [0x00003650] [2019-03-01 16:46:47,618] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x00003650] [2019-03-01 16:46:47,618] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003650] [2019-03-01 16:46:47,619] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00003650] [2019-03-01 16:46:47,803] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00003650] [2019-03-01 16:46:47,804] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003650] [2019-03-01 16:46:47,907] - loaded entity-script:Account(1).
 DEBUG root [0x00003650] [2019-03-01 16:46:47,909] - loaded entity-script:Room(3).
  INFO root [0x00003650] [2019-03-01 16:46:47,909] - TelnetServer server is running on port 50000
  INFO root [0x00003650] [2019-03-01 16:46:48,364] - ---- cellapp is running ----
 DEBUG root [0x00003650] [2019-03-01 16:46:48,364] - Components::process(): Request for the process of identity...
  WARN root [0x00003650] [2019-03-01 16:46:54,514] - EntityApp::checkTickPeriod: tick took 6149% (6.15 seconds)!
  INFO root [0x00003650] [2019-03-01 16:46:55,605] - Components::findComponents: find logger(1)...
  INFO root [0x00003650] [2019-03-01 16:46:55,675] - Components::findComponents: found logger, addr:192.168.0.148:8375
  INFO root [0x00003650] [2019-03-01 16:46:55,676] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00003650] [2019-03-01 16:46:55,676] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003650] [2019-03-01 16:46:55,677] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003650] [2019-03-01 16:46:55,781] - Components::findComponents: found dbmgr, addr:192.168.0.148:8377
  INFO root [0x00003650] [2019-03-01 16:46:55,781] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00003650] [2019-03-01 16:46:55,782] - Components::addComponent[dbmgr], uid=28936, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003650] [2019-03-01 16:46:55,782] - Components::findComponents: found dbmgr, addr:192.168.0.148:8377
  WARN root [0x00003650] [2019-03-01 16:46:56,783] - Forwarding logs to logger[192.168.0.148:8375/0/0/0]...
 ERROR root [0x00003650] [2019-03-01 16:49:28,420] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00003650] [2019-03-01 16:49:28,424] - The following logs sent to logger failed:
  WARN root [0x00003650] [2019-03-01 16:49:28,424] - ==> [2019-03-01 16:49:28 419] TCPPacketReceiver::processPendingEvents(192.168.0.148:8375): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003650] [2019-03-01 16:49:28,424] - ==> [2019-03-01 16:49:28 421] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [0x00003650] [2019-03-01 16:49:28,462] - TCPPacketReceiver::processPendingEvents(192.168.0.148:8377): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003650] [2019-03-01 16:49:28,463] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00003650] [2019-03-01 16:49:28,467] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00003650] [2019-03-01 16:49:28,469] - Shutdowner::onShutdown: shutting down
 S_DBG root [0x00003650] [2019-03-01 16:49:28,472] - Avatar::onDestroy: 2.
 S_ERR root [0x00003650] [2019-03-01 16:49:28,474] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x00003650] [2019-03-01 16:49:28,476] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
 S_DBG root [0x00003650] [2019-03-01 16:49:28,479] - Avatar::onDestroy: 4.
 S_ERR root [0x00003650] [2019-03-01 16:49:28,480] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x00003650] [2019-03-01 16:49:28,481] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
  INFO root [0x00003650] [2019-03-01 16:49:28,483] - Spaces::destroySpace: 1.
 S_DBG root [0x00003650] [2019-03-01 16:49:28,483] - Avatar::onDestroy: 5.
 S_ERR root [0x00003650] [2019-03-01 16:49:28,484] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x00003650] [2019-03-01 16:49:28,485] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
 S_DBG root [0x00003650] [2019-03-01 16:49:28,486] - Avatar::onDestroy: 7.
 S_ERR root [0x00003650] [2019-03-01 16:49:28,486] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x00003650] [2019-03-01 16:49:28,487] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
  INFO root [0x00003650] [2019-03-01 16:49:28,488] - Spaces::destroySpace: 2.
  INFO root [0x00003650] [2019-03-01 16:49:28,489] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00003650] [2019-03-01 16:49:28,489] - Room::~Room(): 6
 DEBUG root [0x00003650] [2019-03-01 16:49:28,489] - Account::~Account(): 5
 DEBUG root [0x00003650] [2019-03-01 16:49:28,490] - Account::~Account(): 7
 DEBUG root [0x00003650] [2019-03-01 16:49:28,490] - Room::~Room(): 3
 DEBUG root [0x00003650] [2019-03-01 16:49:28,490] - Account::~Account(): 2
 DEBUG root [0x00003650] [2019-03-01 16:49:28,490] - Account::~Account(): 4
 DEBUG root [0x00003650] [2019-03-01 16:49:28,491] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x00003650] [2019-03-01 16:49:28,491] - Witness::destroyObjPool(): size 16.
  INFO root [0x00003650] [2019-03-01 16:49:28,526] - Script::uninstall(): is successfully!
 DEBUG root [0x00003650] [2019-03-01 16:49:28,526] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003d0c] [2019-03-01 16:58:37,017] - 
  INFO root [0x00003d0c] [2019-03-01 16:58:37,018] - -----------------------------------------------------------------------------------------


  INFO root [0x00003d0c] [2019-03-01 16:58:37,020] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x00003d0c] [2019-03-01 16:58:37,021] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x00003d0c] [2019-03-01 16:58:37,021] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x00003d0c] [2019-03-01 16:58:37,026] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:7011 )
  INFO root [0x00003d0c] [2019-03-01 16:58:37,027] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:7011, SOMAXCONN=5.
  INFO root [0x00003d0c] [2019-03-01 16:58:37,027] - server-configs:
  INFO root [0x00003d0c] [2019-03-01 16:58:37,027] - 	gameUpdateHertz : 10
  INFO root [0x00003d0c] [2019-03-01 16:58:37,028] - 	defaultViewRadius : 80
  INFO root [0x00003d0c] [2019-03-01 16:58:37,028] - 	defaultViewHysteresisArea : 5
  INFO root [0x00003d0c] [2019-03-01 16:58:37,028] - 	entryScriptFile : kbemain
  INFO root [0x00003d0c] [2019-03-01 16:58:37,029] - 	internalTcpAddr : 192.168.0.148:7011
  INFO root [0x00003d0c] [2019-03-01 16:58:37,029] - 	componentID : 8001
  WARN root [0x00003d0c] [2019-03-01 16:58:37,033] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [0x00003d0c] [2019-03-01 16:58:38,539] - ---- cellapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: E73A667D90DF1EB3CFEA32B1FCE682E5. Config: Debug X86. Built: 17:21:32 Feb 27 2019. AppID: 8001. UID: 28936. PID: 15344 ----
  INFO root [0x00003d0c] [2019-03-01 16:58:38,539] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x00003d0c] [2019-03-01 16:58:38,540] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003d0c] [2019-03-01 16:58:38,540] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00003d0c] [2019-03-01 16:58:38,716] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00003d0c] [2019-03-01 16:58:38,716] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003d0c] [2019-03-01 16:58:38,822] - loaded entity-script:Account(1).
 DEBUG root [0x00003d0c] [2019-03-01 16:58:38,823] - loaded entity-script:Room(3).
  INFO root [0x00003d0c] [2019-03-01 16:58:38,824] - TelnetServer server is running on port 50000
  INFO root [0x00003d0c] [2019-03-01 16:58:39,186] - ---- cellapp is running ----
 DEBUG root [0x00003d0c] [2019-03-01 16:58:39,186] - Components::process(): Request for the process of identity...
  WARN root [0x00003d0c] [2019-03-01 16:58:45,345] - EntityApp::checkTickPeriod: tick took 6158% (6.16 seconds)!
  INFO root [0x00003d0c] [2019-03-01 16:58:46,387] - Components::findComponents: find logger(1)...
  INFO root [0x00003d0c] [2019-03-01 16:58:46,426] - Components::findComponents: found logger, addr:192.168.0.148:7005
  INFO root [0x00003d0c] [2019-03-01 16:58:46,427] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00003d0c] [2019-03-01 16:58:46,427] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003d0c] [2019-03-01 16:58:46,430] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003d0c] [2019-03-01 16:58:46,533] - Components::findComponents: found dbmgr, addr:192.168.0.148:7007
  INFO root [0x00003d0c] [2019-03-01 16:58:46,533] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00003d0c] [2019-03-01 16:58:46,534] - Components::addComponent[dbmgr], uid=28936, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003d0c] [2019-03-01 16:58:46,534] - Components::findComponents: found dbmgr, addr:192.168.0.148:7007
  WARN root [0x00003d0c] [2019-03-01 16:58:47,535] - EntityApp::checkTickPeriod: tick took 1248% (1.25 seconds)!
  WARN root [0x00003d0c] [2019-03-01 16:58:47,536] - Forwarding logs to logger[192.168.0.148:7005/0/0/0]...
 ERROR root [0x00003d0c] [2019-03-01 17:08:43,559] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00003d0c] [2019-03-01 17:08:43,563] - The following logs sent to logger failed:
  WARN root [0x00003d0c] [2019-03-01 17:08:43,564] - ==> [2019-03-01 17:08:43 558] TCPPacketReceiver::processPendingEvents(192.168.0.148:7005): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003d0c] [2019-03-01 17:08:43,564] - ==> [2019-03-01 17:08:43 559] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [0x00003d0c] [2019-03-01 17:08:43,605] - TCPPacketReceiver::processPendingEvents(192.168.0.148:7007): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003d0c] [2019-03-01 17:08:43,606] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00003d0c] [2019-03-01 17:08:43,611] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00003d0c] [2019-03-01 17:08:43,614] - Shutdowner::onShutdown: shutting down
 S_DBG root [0x00003d0c] [2019-03-01 17:08:43,614] - Avatar::onDestroy: 2.
 S_ERR root [0x00003d0c] [2019-03-01 17:08:43,614] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x00003d0c] [2019-03-01 17:08:43,614] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
 S_DBG root [0x00003d0c] [2019-03-01 17:08:43,619] - Avatar::onDestroy: 4.
 S_ERR root [0x00003d0c] [2019-03-01 17:08:43,619] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x00003d0c] [2019-03-01 17:08:43,619] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
  INFO root [0x00003d0c] [2019-03-01 17:08:43,619] - Spaces::destroySpace: 1.
 S_DBG root [0x00003d0c] [2019-03-01 17:08:43,619] - Avatar::onDestroy: 5.
 S_ERR root [0x00003d0c] [2019-03-01 17:08:43,619] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x00003d0c] [2019-03-01 17:08:43,619] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
 S_DBG root [0x00003d0c] [2019-03-01 17:08:43,619] - Avatar::onDestroy: 7.
 S_ERR root [0x00003d0c] [2019-03-01 17:08:43,619] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x00003d0c] [2019-03-01 17:08:43,619] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
  INFO root [0x00003d0c] [2019-03-01 17:08:43,619] - Spaces::destroySpace: 2.
  INFO root [0x00003d0c] [2019-03-01 17:08:43,619] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00003d0c] [2019-03-01 17:08:43,619] - Room::~Room(): 6
 DEBUG root [0x00003d0c] [2019-03-01 17:08:43,619] - Account::~Account(): 5
 DEBUG root [0x00003d0c] [2019-03-01 17:08:43,619] - Account::~Account(): 7
 DEBUG root [0x00003d0c] [2019-03-01 17:08:43,619] - Room::~Room(): 3
 DEBUG root [0x00003d0c] [2019-03-01 17:08:43,619] - Account::~Account(): 2
 DEBUG root [0x00003d0c] [2019-03-01 17:08:43,629] - Account::~Account(): 4
 DEBUG root [0x00003d0c] [2019-03-01 17:08:43,629] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x00003d0c] [2019-03-01 17:08:43,629] - Witness::destroyObjPool(): size 16.
  INFO root [0x00003d0c] [2019-03-01 17:08:43,651] - Script::uninstall(): is successfully!
 DEBUG root [0x00003d0c] [2019-03-01 17:08:43,651] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00001d64] [2019-03-01 17:10:29,696] - 
  INFO root [0x00001d64] [2019-03-01 17:10:29,699] - -----------------------------------------------------------------------------------------


  INFO root [0x00001d64] [2019-03-01 17:10:29,701] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x00001d64] [2019-03-01 17:10:29,702] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x00001d64] [2019-03-01 17:10:29,702] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x00001d64] [2019-03-01 17:10:29,713] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:8948 )
  INFO root [0x00001d64] [2019-03-01 17:10:29,713] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:8948, SOMAXCONN=5.
  INFO root [0x00001d64] [2019-03-01 17:10:29,714] - server-configs:
  INFO root [0x00001d64] [2019-03-01 17:10:29,714] - 	gameUpdateHertz : 10
  INFO root [0x00001d64] [2019-03-01 17:10:29,714] - 	defaultViewRadius : 80
  INFO root [0x00001d64] [2019-03-01 17:10:29,714] - 	defaultViewHysteresisArea : 5
  INFO root [0x00001d64] [2019-03-01 17:10:29,714] - 	entryScriptFile : kbemain
  INFO root [0x00001d64] [2019-03-01 17:10:29,715] - 	internalTcpAddr : 192.168.0.148:8948
  INFO root [0x00001d64] [2019-03-01 17:10:29,715] - 	componentID : 8001
  WARN root [0x00001d64] [2019-03-01 17:10:29,721] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [0x00001d64] [2019-03-01 17:10:31,232] - ---- cellapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: E73A667D90DF1EB3CFEA32B1FCE682E5. Config: Debug X86. Built: 17:21:32 Feb 27 2019. AppID: 8001. UID: 28936. PID: 15600 ----
  INFO root [0x00001d64] [2019-03-01 17:10:31,232] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x00001d64] [2019-03-01 17:10:31,233] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001d64] [2019-03-01 17:10:31,233] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00001d64] [2019-03-01 17:10:31,419] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00001d64] [2019-03-01 17:10:31,419] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00001d64] [2019-03-01 17:10:31,508] - loaded entity-script:Account(1).
 DEBUG root [0x00001d64] [2019-03-01 17:10:31,509] - loaded entity-script:Room(3).
  INFO root [0x00001d64] [2019-03-01 17:10:31,510] - TelnetServer server is running on port 50000
  INFO root [0x00001d64] [2019-03-01 17:10:31,871] - ---- cellapp is running ----
 DEBUG root [0x00001d64] [2019-03-01 17:10:31,872] - Components::process(): Request for the process of identity...
  WARN root [0x00001d64] [2019-03-01 17:10:38,008] - EntityApp::checkTickPeriod: tick took 6137% (6.14 seconds)!
  INFO root [0x00001d64] [2019-03-01 17:10:39,107] - Components::findComponents: find logger(1)...
  INFO root [0x00001d64] [2019-03-01 17:10:39,132] - Components::findComponents: found logger, addr:192.168.0.148:8950
  INFO root [0x00001d64] [2019-03-01 17:10:39,133] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00001d64] [2019-03-01 17:10:39,133] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001d64] [2019-03-01 17:10:39,135] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00001d64] [2019-03-01 17:10:39,237] - Components::findComponents: found dbmgr, addr:192.168.0.148:8946
  INFO root [0x00001d64] [2019-03-01 17:10:39,237] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00001d64] [2019-03-01 17:10:39,237] - Components::addComponent[dbmgr], uid=28936, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001d64] [2019-03-01 17:10:39,237] - Components::findComponents: found dbmgr, addr:192.168.0.148:8946
  WARN root [0x00001d64] [2019-03-01 17:10:40,238] - Forwarding logs to logger[192.168.0.148:8950/0/0/0]...
 ERROR root [0x00001d64] [2019-03-01 17:15:27,481] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00001d64] [2019-03-01 17:15:27,484] - The following logs sent to logger failed:
  WARN root [0x00001d64] [2019-03-01 17:15:27,485] - ==> [2019-03-01 17:15:27 481] TCPPacketReceiver::processPendingEvents(192.168.0.148:8950): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001d64] [2019-03-01 17:15:27,485] - ==> [2019-03-01 17:15:27 482] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [0x00001d64] [2019-03-01 17:15:27,533] - TCPPacketReceiver::processPendingEvents(192.168.0.148:8946): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001d64] [2019-03-01 17:15:27,534] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00001d64] [2019-03-01 17:15:27,540] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00001d64] [2019-03-01 17:15:27,543] - Shutdowner::onShutdown: shutting down
 S_DBG root [0x00001d64] [2019-03-01 17:15:27,544] - Avatar::onDestroy: 2.
 S_ERR root [0x00001d64] [2019-03-01 17:15:27,545] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x00001d64] [2019-03-01 17:15:27,548] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
 S_DBG root [0x00001d64] [2019-03-01 17:15:27,551] - Avatar::onDestroy: 4.
 S_ERR root [0x00001d64] [2019-03-01 17:15:27,552] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x00001d64] [2019-03-01 17:15:27,553] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
  INFO root [0x00001d64] [2019-03-01 17:15:27,554] - Spaces::destroySpace: 1.
  INFO root [0x00001d64] [2019-03-01 17:15:27,555] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00001d64] [2019-03-01 17:15:27,555] - Room::~Room(): 3
 DEBUG root [0x00001d64] [2019-03-01 17:15:27,555] - Account::~Account(): 2
 DEBUG root [0x00001d64] [2019-03-01 17:15:27,556] - Account::~Account(): 4
 DEBUG root [0x00001d64] [2019-03-01 17:15:27,556] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x00001d64] [2019-03-01 17:15:27,556] - Witness::destroyObjPool(): size 16.
  INFO root [0x00001d64] [2019-03-01 17:15:27,574] - Script::uninstall(): is successfully!
 DEBUG root [0x00001d64] [2019-03-01 17:15:27,575] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000007f4] [2019-03-01 17:30:39,881] - 
  INFO root [0x000007f4] [2019-03-01 17:30:39,882] - -----------------------------------------------------------------------------------------


  INFO root [0x000007f4] [2019-03-01 17:30:39,883] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x000007f4] [2019-03-01 17:30:39,883] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x000007f4] [2019-03-01 17:30:39,883] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x000007f4] [2019-03-01 17:30:39,887] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:12238 )
  INFO root [0x000007f4] [2019-03-01 17:30:39,888] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:12238, SOMAXCONN=5.
  INFO root [0x000007f4] [2019-03-01 17:30:39,888] - server-configs:
  INFO root [0x000007f4] [2019-03-01 17:30:39,888] - 	gameUpdateHertz : 10
  INFO root [0x000007f4] [2019-03-01 17:30:39,889] - 	defaultViewRadius : 80
  INFO root [0x000007f4] [2019-03-01 17:30:39,889] - 	defaultViewHysteresisArea : 5
  INFO root [0x000007f4] [2019-03-01 17:30:39,889] - 	entryScriptFile : kbemain
  INFO root [0x000007f4] [2019-03-01 17:30:39,889] - 	internalTcpAddr : 192.168.0.148:12238
  INFO root [0x000007f4] [2019-03-01 17:30:39,889] - 	componentID : 8001
  WARN root [0x000007f4] [2019-03-01 17:30:39,894] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [0x000007f4] [2019-03-01 17:30:41,400] - ---- cellapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: E73A667D90DF1EB3CFEA32B1FCE682E5. Config: Debug X86. Built: 17:21:32 Feb 27 2019. AppID: 8001. UID: 28936. PID: 14740 ----
  INFO root [0x000007f4] [2019-03-01 17:30:41,400] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x000007f4] [2019-03-01 17:30:41,400] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000007f4] [2019-03-01 17:30:41,401] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x000007f4] [2019-03-01 17:30:41,607] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x000007f4] [2019-03-01 17:30:41,607] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000007f4] [2019-03-01 17:30:41,715] - loaded entity-script:Account(1).
 DEBUG root [0x000007f4] [2019-03-01 17:30:41,716] - loaded entity-script:Room(3).
  INFO root [0x000007f4] [2019-03-01 17:30:41,717] - TelnetServer server is running on port 50000
  INFO root [0x000007f4] [2019-03-01 17:30:42,169] - ---- cellapp is running ----
 DEBUG root [0x000007f4] [2019-03-01 17:30:42,170] - Components::process(): Request for the process of identity...
  WARN root [0x000007f4] [2019-03-01 17:30:48,319] - EntityApp::checkTickPeriod: tick took 6149% (6.15 seconds)!
  INFO root [0x000007f4] [2019-03-01 17:30:49,370] - Components::findComponents: find logger(1)...
  INFO root [0x000007f4] [2019-03-01 17:30:49,393] - Components::findComponents: found logger, addr:192.168.0.148:12233
  INFO root [0x000007f4] [2019-03-01 17:30:49,393] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x000007f4] [2019-03-01 17:30:49,393] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000007f4] [2019-03-01 17:30:49,395] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000007f4] [2019-03-01 17:30:49,499] - Components::findComponents: found dbmgr, addr:192.168.0.148:12235
  INFO root [0x000007f4] [2019-03-01 17:30:49,499] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x000007f4] [2019-03-01 17:30:49,500] - Components::addComponent[dbmgr], uid=28936, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000007f4] [2019-03-01 17:30:49,500] - Components::findComponents: found dbmgr, addr:192.168.0.148:12235
  WARN root [0x000007f4] [2019-03-01 17:30:50,501] - EntityApp::checkTickPeriod: tick took 1230% (1.23 seconds)!
  WARN root [0x000007f4] [2019-03-01 17:30:50,501] - Forwarding logs to logger[192.168.0.148:12233/0/0/0]...
 ERROR root [0x000007f4] [2019-03-01 17:37:13,686] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x000007f4] [2019-03-01 17:37:13,689] - The following logs sent to logger failed:
  WARN root [0x000007f4] [2019-03-01 17:37:13,689] - ==> [2019-03-01 17:37:13 686] TCPPacketReceiver::processPendingEvents(192.168.0.148:12233): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000007f4] [2019-03-01 17:37:13,690] - ==> [2019-03-01 17:37:13 687] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [0x000007f4] [2019-03-01 17:37:13,731] - TCPPacketReceiver::processPendingEvents(192.168.0.148:12235): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000007f4] [2019-03-01 17:37:13,732] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x000007f4] [2019-03-01 17:37:13,735] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x000007f4] [2019-03-01 17:37:13,738] - Shutdowner::onShutdown: shutting down
 S_DBG root [0x000007f4] [2019-03-01 17:37:13,739] - Avatar::onDestroy: 2.
 S_ERR root [0x000007f4] [2019-03-01 17:37:13,740] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x000007f4] [2019-03-01 17:37:13,742] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
 S_DBG root [0x000007f4] [2019-03-01 17:37:13,743] - Avatar::onDestroy: 4.
 S_ERR root [0x000007f4] [2019-03-01 17:37:13,745] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x000007f4] [2019-03-01 17:37:13,746] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
  INFO root [0x000007f4] [2019-03-01 17:37:13,752] - Spaces::destroySpace: 1.
 S_DBG root [0x000007f4] [2019-03-01 17:37:13,753] - Avatar::onDestroy: 5.
 S_ERR root [0x000007f4] [2019-03-01 17:37:13,753] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x000007f4] [2019-03-01 17:37:13,754] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
 S_DBG root [0x000007f4] [2019-03-01 17:37:13,755] - Avatar::onDestroy: 7.
 S_ERR root [0x000007f4] [2019-03-01 17:37:13,756] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x000007f4] [2019-03-01 17:37:13,757] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
  INFO root [0x000007f4] [2019-03-01 17:37:13,758] - Spaces::destroySpace: 2.
  INFO root [0x000007f4] [2019-03-01 17:37:13,758] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x000007f4] [2019-03-01 17:37:13,759] - Room::~Room(): 6
 DEBUG root [0x000007f4] [2019-03-01 17:37:13,759] - Account::~Account(): 5
 DEBUG root [0x000007f4] [2019-03-01 17:37:13,759] - Account::~Account(): 7
 DEBUG root [0x000007f4] [2019-03-01 17:37:13,759] - Room::~Room(): 3
 DEBUG root [0x000007f4] [2019-03-01 17:37:13,760] - Account::~Account(): 2
 DEBUG root [0x000007f4] [2019-03-01 17:37:13,760] - Account::~Account(): 4
 DEBUG root [0x000007f4] [2019-03-01 17:37:13,760] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x000007f4] [2019-03-01 17:37:13,760] - Witness::destroyObjPool(): size 16.
  INFO root [0x000007f4] [2019-03-01 17:37:13,779] - Script::uninstall(): is successfully!
 DEBUG root [0x000007f4] [2019-03-01 17:37:13,780] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003b38] [2019-03-01 18:55:01,622] - 
  INFO root [0x00003b38] [2019-03-01 18:55:01,622] - -----------------------------------------------------------------------------------------


  INFO root [0x00003b38] [2019-03-01 18:55:01,622] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x00003b38] [2019-03-01 18:55:01,628] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x00003b38] [2019-03-01 18:55:01,628] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x00003b38] [2019-03-01 18:55:01,632] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:9441 )
  INFO root [0x00003b38] [2019-03-01 18:55:01,632] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:9441, SOMAXCONN=5.
  INFO root [0x00003b38] [2019-03-01 18:55:01,632] - server-configs:
  INFO root [0x00003b38] [2019-03-01 18:55:01,632] - 	gameUpdateHertz : 10
  INFO root [0x00003b38] [2019-03-01 18:55:01,632] - 	defaultViewRadius : 80
  INFO root [0x00003b38] [2019-03-01 18:55:01,632] - 	defaultViewHysteresisArea : 5
  INFO root [0x00003b38] [2019-03-01 18:55:01,632] - 	entryScriptFile : kbemain
  INFO root [0x00003b38] [2019-03-01 18:55:01,632] - 	internalTcpAddr : 192.168.0.148:9441
  INFO root [0x00003b38] [2019-03-01 18:55:01,632] - 	componentID : 8001
  WARN root [0x00003b38] [2019-03-01 18:55:01,638] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  WARN root [0x00003b38] [2019-03-01 18:55:02,268] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20375, errorno=10048
  INFO root [0x00003b38] [2019-03-01 18:55:02,269] - ---- cellapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: E73A667D90DF1EB3CFEA32B1FCE682E5. Config: Debug X86. Built: 17:21:32 Feb 27 2019. AppID: 8001. UID: 28936. PID: 7872 ----
  INFO root [0x00003b38] [2019-03-01 18:55:02,269] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x00003b38] [2019-03-01 18:55:02,269] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003b38] [2019-03-01 18:55:02,269] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00003b38] [2019-03-01 18:55:02,464] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00003b38] [2019-03-01 18:55:02,464] - Script::install(): KBExtra is successfully!
 ERROR root [0x00003b38] [2019-03-01 18:55:02,469] - TiXmlNode::openXML: D:/kbengine-2.4.2/first_server_assets/scripts/entity_defs/Room.def, error!
 ERROR root [0x00003b38] [2019-03-01 18:55:02,475] - app::initialize(): initialization failed!
 DEBUG root [0x00003b38] [2019-03-01 18:55:02,475] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00003b38] [2019-03-01 18:55:02,475] - Witness::destroyObjPool(): size 0.
  INFO root [0x00003b38] [2019-03-01 18:55:02,478] - Script::uninstall(): is successfully!
 DEBUG root [0x00003b38] [2019-03-01 18:55:02,478] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00003b38] [2019-03-01 18:55:02,788] - ThreadPool::destroy(): waiting for thread(2)[0x26f0280,0x26f0900,], try=1
 DEBUG root [0x00003b38] [2019-03-01 18:55:03,228] - TPThread::~TPThread(): 0x26f0280
 DEBUG root [0x00003b38] [2019-03-01 18:55:03,228] - TPThread::~TPThread(): 0x26f0900
 DEBUG root [0x00003b38] [2019-03-01 18:55:03,228] - ThreadPool::destroy(): successfully!
 DEBUG root [0x00003b38] [2019-03-01 18:55:03,228] - Bundle::destroyObjPool(): size 1.
 DEBUG root [0x00003b38] [2019-03-01 18:55:03,228] - Channel::destroyObjPool(): size 0.
 DEBUG root [0x00003b38] [2019-03-01 18:55:03,228] - TCPPacket::destroyObjPool(): size 0.
 DEBUG root [0x00003b38] [2019-03-01 18:55:03,228] - UDPPacket::destroyObjPool(): size 15.
 DEBUG root [0x00003b38] [2019-03-01 18:55:03,228] - EndPoint::destroyObjPool(): size 0.
 DEBUG root [0x00003b38] [2019-03-01 18:55:03,228] - Address::destroyObjPool(): size 0.
 DEBUG root [0x00003b38] [2019-03-01 18:55:03,228] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [0x00003b38] [2019-03-01 18:55:03,228] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [0x00003b38] [2019-03-01 18:55:09,778] - EventDispatcher()::~EventDispatcher: Num timers = 1
  INFO root [0x0000371c] [2019-03-01 18:56:17,591] - 
  INFO root [0x0000371c] [2019-03-01 18:56:17,591] - -----------------------------------------------------------------------------------------


  INFO root [0x0000371c] [2019-03-01 18:56:17,591] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x0000371c] [2019-03-01 18:56:17,591] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x0000371c] [2019-03-01 18:56:17,591] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x0000371c] [2019-03-01 18:56:17,603] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:9664 )
  INFO root [0x0000371c] [2019-03-01 18:56:17,604] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:9664, SOMAXCONN=5.
  INFO root [0x0000371c] [2019-03-01 18:56:17,604] - server-configs:
  INFO root [0x0000371c] [2019-03-01 18:56:17,604] - 	gameUpdateHertz : 10
  INFO root [0x0000371c] [2019-03-01 18:56:17,604] - 	defaultViewRadius : 80
  INFO root [0x0000371c] [2019-03-01 18:56:17,605] - 	defaultViewHysteresisArea : 5
  INFO root [0x0000371c] [2019-03-01 18:56:17,605] - 	entryScriptFile : kbemain
  INFO root [0x0000371c] [2019-03-01 18:56:17,605] - 	internalTcpAddr : 192.168.0.148:9664
  INFO root [0x0000371c] [2019-03-01 18:56:17,605] - 	componentID : 8001
  WARN root [0x0000371c] [2019-03-01 18:56:17,608] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [0x0000371c] [2019-03-01 18:56:19,128] - ---- cellapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: E73A667D90DF1EB3CFEA32B1FCE682E5. Config: Debug X86. Built: 17:21:32 Feb 27 2019. AppID: 8001. UID: 28936. PID: 8660 ----
  INFO root [0x0000371c] [2019-03-01 18:56:19,128] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x0000371c] [2019-03-01 18:56:19,128] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x0000371c] [2019-03-01 18:56:19,128] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x0000371c] [2019-03-01 18:56:19,321] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x0000371c] [2019-03-01 18:56:19,321] - Script::install(): KBExtra is successfully!
 DEBUG root [0x0000371c] [2019-03-01 18:56:19,400] - loaded entity-script:Account(1).
  WARN root [0x0000371c] [2019-03-01 18:56:19,400] - EntityDef::checkDefMethod: exposed of method: Room.enterGameWorld, check the caller can use "def enterGameWorld(self, callerID, ...)", such as: if callerID == self.id!
 DEBUG root [0x0000371c] [2019-03-01 18:56:19,400] - loaded entity-script:Room(3).
  INFO root [0x0000371c] [2019-03-01 18:56:19,400] - TelnetServer server is running on port 50000
  INFO root [0x0000371c] [2019-03-01 18:56:19,728] - ---- cellapp is running ----
 DEBUG root [0x0000371c] [2019-03-01 18:56:19,728] - Components::process(): Request for the process of identity...
  WARN root [0x0000371c] [2019-03-01 18:56:26,001] - EntityApp::checkTickPeriod: tick took 6268% (6.27 seconds)!
  INFO root [0x0000371c] [2019-03-01 18:56:27,048] - Components::findComponents: find logger(1)...
  INFO root [0x0000371c] [2019-03-01 18:56:27,161] - Components::findComponents: found logger, addr:192.168.0.148:9663
  INFO root [0x0000371c] [2019-03-01 18:56:27,161] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x0000371c] [2019-03-01 18:56:27,161] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000371c] [2019-03-01 18:56:27,161] - Components::findComponents: find dbmgr(2)...
  INFO root [0x0000371c] [2019-03-01 18:56:27,278] - Components::findComponents: found dbmgr, addr:192.168.0.148:9657
  INFO root [0x0000371c] [2019-03-01 18:56:27,288] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x0000371c] [2019-03-01 18:56:27,288] - Components::addComponent[dbmgr], uid=28936, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000371c] [2019-03-01 18:56:27,288] - Components::findComponents: found dbmgr, addr:192.168.0.148:9657
  WARN root [0x0000371c] [2019-03-01 18:56:28,288] - EntityApp::checkTickPeriod: tick took 1340% (1.34 seconds)!
  WARN root [0x0000371c] [2019-03-01 18:56:28,288] - Forwarding logs to logger[192.168.0.148:9663/0/0/0]...
 ERROR root [0x0000371c] [2019-03-01 19:03:55,305] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x0000371c] [2019-03-01 19:03:55,310] - The following logs sent to logger failed:
  WARN root [0x0000371c] [2019-03-01 19:03:55,310] - ==> [2019-03-01 19:03:55 305] TCPPacketReceiver::processPendingEvents(192.168.0.148:9663): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000371c] [2019-03-01 19:03:55,311] - ==> [2019-03-01 19:03:55 307] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [0x0000371c] [2019-03-01 19:03:55,348] - TCPPacketReceiver::processPendingEvents(192.168.0.148:9657): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000371c] [2019-03-01 19:03:55,348] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x0000371c] [2019-03-01 19:03:55,358] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x0000371c] [2019-03-01 19:03:55,358] - Shutdowner::onShutdown: shutting down
  INFO root [0x0000371c] [2019-03-01 19:03:55,358] - Spaces::destroySpace: 1.
  INFO root [0x0000371c] [2019-03-01 19:03:55,358] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x0000371c] [2019-03-01 19:03:55,358] - Room::~Room(): 3
 DEBUG root [0x0000371c] [2019-03-01 19:03:55,358] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x0000371c] [2019-03-01 19:03:55,358] - Witness::destroyObjPool(): size 0.
  INFO root [0x0000371c] [2019-03-01 19:03:55,378] - Script::uninstall(): is successfully!
 DEBUG root [0x0000371c] [2019-03-01 19:03:55,378] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00000930] [2019-03-01 19:04:54,726] - 
  INFO root [0x00000930] [2019-03-01 19:04:54,726] - -----------------------------------------------------------------------------------------


  INFO root [0x00000930] [2019-03-01 19:04:54,729] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x00000930] [2019-03-01 19:04:54,729] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x00000930] [2019-03-01 19:04:54,729] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x00000930] [2019-03-01 19:04:54,729] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:10898 )
  INFO root [0x00000930] [2019-03-01 19:04:54,729] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:10898, SOMAXCONN=5.
  INFO root [0x00000930] [2019-03-01 19:04:54,729] - server-configs:
  INFO root [0x00000930] [2019-03-01 19:04:54,729] - 	gameUpdateHertz : 10
  INFO root [0x00000930] [2019-03-01 19:04:54,729] - 	defaultViewRadius : 80
  INFO root [0x00000930] [2019-03-01 19:04:54,729] - 	defaultViewHysteresisArea : 5
  INFO root [0x00000930] [2019-03-01 19:04:54,729] - 	entryScriptFile : kbemain
  INFO root [0x00000930] [2019-03-01 19:04:54,729] - 	internalTcpAddr : 192.168.0.148:10898
  INFO root [0x00000930] [2019-03-01 19:04:54,729] - 	componentID : 8001
  WARN root [0x00000930] [2019-03-01 19:04:54,729] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  WARN root [0x00000930] [2019-03-01 19:04:55,248] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20855, errorno=10048
  INFO root [0x00000930] [2019-03-01 19:04:55,248] - ---- cellapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: E73A667D90DF1EB3CFEA32B1FCE682E5. Config: Debug X86. Built: 17:21:32 Feb 27 2019. AppID: 8001. UID: 28936. PID: 4076 ----
  INFO root [0x00000930] [2019-03-01 19:04:55,248] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x00000930] [2019-03-01 19:04:55,252] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00000930] [2019-03-01 19:04:55,252] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00000930] [2019-03-01 19:04:55,438] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00000930] [2019-03-01 19:04:55,438] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00000930] [2019-03-01 19:04:55,532] - loaded entity-script:Account(1).
  WARN root [0x00000930] [2019-03-01 19:04:55,532] - EntityDef::checkDefMethod: exposed of method: Room.enterGameWorld, check the caller can use "def enterGameWorld(self, callerID, ...)", such as: if callerID == self.id!
 DEBUG root [0x00000930] [2019-03-01 19:04:55,532] - loaded entity-script:Room(3).
  INFO root [0x00000930] [2019-03-01 19:04:55,532] - TelnetServer server is running on port 50000
  INFO root [0x00000930] [2019-03-01 19:04:55,957] - ---- cellapp is running ----
 DEBUG root [0x00000930] [2019-03-01 19:04:55,957] - Components::process(): Request for the process of identity...
  WARN root [0x00000930] [2019-03-01 19:05:02,188] - EntityApp::checkTickPeriod: tick took 6233% (6.23 seconds)!
  WARN root [0x00000930] [2019-03-01 19:05:02,198] - TCPPacketReceiver::processPendingEvents(192.168.0.148:10917): Throwing REASON_GENERAL_NETWORK - WSAECONNABORTED
  INFO root [0x00000930] [2019-03-01 19:05:03,248] - Components::findComponents: find logger(1)...
  INFO root [0x00000930] [2019-03-01 19:05:03,308] - Components::findComponents: found logger, addr:192.168.0.148:10892
  INFO root [0x00000930] [2019-03-01 19:05:03,308] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00000930] [2019-03-01 19:05:03,308] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00000930] [2019-03-01 19:05:03,308] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00000930] [2019-03-01 19:05:03,428] - Components::findComponents: found dbmgr, addr:192.168.0.148:10893
  INFO root [0x00000930] [2019-03-01 19:05:03,428] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00000930] [2019-03-01 19:05:03,428] - Components::addComponent[dbmgr], uid=28936, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00000930] [2019-03-01 19:05:03,428] - Components::findComponents: found dbmgr, addr:192.168.0.148:10893
  WARN root [0x00000930] [2019-03-01 19:05:04,446] - Forwarding logs to logger[192.168.0.148:10892/0/0/0]...
 ERROR root [0x00000930] [2019-03-01 19:05:56,619] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00000930] [2019-03-01 19:05:56,621] - The following logs sent to logger failed:
  WARN root [0x00000930] [2019-03-01 19:05:56,622] - ==> [2019-03-01 19:05:56 619] TCPPacketReceiver::processPendingEvents(192.168.0.148:10892): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00000930] [2019-03-01 19:05:56,622] - ==> [2019-03-01 19:05:56 619] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00001a74] [2019-03-01 19:06:00,632] - 
  INFO root [0x00001a74] [2019-03-01 19:06:00,632] - -----------------------------------------------------------------------------------------


  INFO root [0x00001a74] [2019-03-01 19:06:00,634] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x00001a74] [2019-03-01 19:06:00,635] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x00001a74] [2019-03-01 19:06:00,635] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x00001a74] [2019-03-01 19:06:00,640] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:10980 )
  INFO root [0x00001a74] [2019-03-01 19:06:00,641] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:10980, SOMAXCONN=5.
  INFO root [0x00001a74] [2019-03-01 19:06:00,641] - server-configs:
  INFO root [0x00001a74] [2019-03-01 19:06:00,641] - 	gameUpdateHertz : 10
  INFO root [0x00001a74] [2019-03-01 19:06:00,641] - 	defaultViewRadius : 80
  INFO root [0x00001a74] [2019-03-01 19:06:00,642] - 	defaultViewHysteresisArea : 5
  INFO root [0x00001a74] [2019-03-01 19:06:00,642] - 	entryScriptFile : kbemain
  INFO root [0x00001a74] [2019-03-01 19:06:00,642] - 	internalTcpAddr : 192.168.0.148:10980
  INFO root [0x00001a74] [2019-03-01 19:06:00,642] - 	componentID : 8001
  WARN root [0x00001a74] [2019-03-01 19:06:00,646] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [0x00001a74] [2019-03-01 19:06:02,168] - ---- cellapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: E73A667D90DF1EB3CFEA32B1FCE682E5. Config: Debug X86. Built: 17:21:32 Feb 27 2019. AppID: 8001. UID: 28936. PID: 7852 ----
  INFO root [0x00001a74] [2019-03-01 19:06:02,168] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x00001a74] [2019-03-01 19:06:02,168] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001a74] [2019-03-01 19:06:02,168] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00001a74] [2019-03-01 19:06:02,358] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00001a74] [2019-03-01 19:06:02,358] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00001a74] [2019-03-01 19:06:02,442] - loaded entity-script:Account(1).
  WARN root [0x00001a74] [2019-03-01 19:06:02,442] - EntityDef::checkDefMethod: exposed of method: Room.enterGameWorld, check the caller can use "def enterGameWorld(self, callerID, ...)", such as: if callerID == self.id!
 DEBUG root [0x00001a74] [2019-03-01 19:06:02,442] - loaded entity-script:Room(3).
  INFO root [0x00001a74] [2019-03-01 19:06:02,442] - TelnetServer server is running on port 50000
  INFO root [0x00001a74] [2019-03-01 19:06:02,799] - ---- cellapp is running ----
 DEBUG root [0x00001a74] [2019-03-01 19:06:02,806] - Components::process(): Request for the process of identity...
  WARN root [0x00001a74] [2019-03-01 19:06:09,111] - EntityApp::checkTickPeriod: tick took 6306% (6.31 seconds)!
  INFO root [0x00001a74] [2019-03-01 19:06:10,148] - Components::findComponents: find logger(1)...
  INFO root [0x00001a74] [2019-03-01 19:06:10,258] - Components::findComponents: found logger, addr:192.168.0.148:10982
  INFO root [0x00001a74] [2019-03-01 19:06:10,258] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00001a74] [2019-03-01 19:06:10,258] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001a74] [2019-03-01 19:06:10,258] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00001a74] [2019-03-01 19:06:10,371] - Components::findComponents: found dbmgr, addr:192.168.0.148:10976
  INFO root [0x00001a74] [2019-03-01 19:06:10,378] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00001a74] [2019-03-01 19:06:10,378] - Components::addComponent[dbmgr], uid=28936, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001a74] [2019-03-01 19:06:10,378] - Components::findComponents: found dbmgr, addr:192.168.0.148:10976
  WARN root [0x00001a74] [2019-03-01 19:06:11,388] - Forwarding logs to logger[192.168.0.148:10982/0/0/0]...
 ERROR root [0x00001a74] [2019-03-01 19:09:30,817] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00001a74] [2019-03-01 19:09:30,821] - The following logs sent to logger failed:
  WARN root [0x00001a74] [2019-03-01 19:09:30,822] - ==> [2019-03-01 19:09:30 815] TCPPacketReceiver::processPendingEvents(192.168.0.148:10982): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001a74] [2019-03-01 19:09:30,823] - ==> [2019-03-01 19:09:30 818] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [0x00001a74] [2019-03-01 19:09:30,860] - TCPPacketReceiver::processPendingEvents(192.168.0.148:10976): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001a74] [2019-03-01 19:09:30,861] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00001a74] [2019-03-01 19:09:30,867] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00001a74] [2019-03-01 19:09:30,869] - Shutdowner::onShutdown: shutting down
  INFO root [0x00001a74] [2019-03-01 19:09:30,871] - Spaces::destroySpace: 1.
  INFO root [0x00001a74] [2019-03-01 19:09:30,872] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00001a74] [2019-03-01 19:09:30,872] - Room::~Room(): 3
 DEBUG root [0x00001a74] [2019-03-01 19:09:30,873] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00001a74] [2019-03-01 19:09:30,874] - Witness::destroyObjPool(): size 0.
  INFO root [0x00001a74] [2019-03-01 19:09:30,901] - Script::uninstall(): is successfully!
 DEBUG root [0x00001a74] [2019-03-01 19:09:30,902] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003e70] [2019-03-01 19:09:35,171] - 
  INFO root [0x00003e70] [2019-03-01 19:09:35,172] - -----------------------------------------------------------------------------------------


  INFO root [0x00003e70] [2019-03-01 19:09:35,174] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [0x00003e70] [2019-03-01 19:09:35,175] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [0x00003e70] [2019-03-01 19:09:35,175] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [0x00003e70] [2019-03-01 19:09:35,181] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:11081 )
  INFO root [0x00003e70] [2019-03-01 19:09:35,181] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:11081, SOMAXCONN=5.
  INFO root [0x00003e70] [2019-03-01 19:09:35,182] - server-configs:
  INFO root [0x00003e70] [2019-03-01 19:09:35,182] - 	gameUpdateHertz : 10
  INFO root [0x00003e70] [2019-03-01 19:09:35,182] - 	defaultViewRadius : 80
  INFO root [0x00003e70] [2019-03-01 19:09:35,182] - 	defaultViewHysteresisArea : 5
  INFO root [0x00003e70] [2019-03-01 19:09:35,182] - 	entryScriptFile : kbemain
  INFO root [0x00003e70] [2019-03-01 19:09:35,182] - 	internalTcpAddr : 192.168.0.148:11081
  INFO root [0x00003e70] [2019-03-01 19:09:35,182] - 	componentID : 8001
  WARN root [0x00003e70] [2019-03-01 19:09:35,186] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  WARN root [0x00003e70] [2019-03-01 19:09:35,527] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20196, errorno=10048
  INFO root [0x00003e70] [2019-03-01 19:09:35,530] - ---- cellapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: E73A667D90DF1EB3CFEA32B1FCE682E5. Config: Debug X86. Built: 17:21:32 Feb 27 2019. AppID: 8001. UID: 28936. PID: 6192 ----
  INFO root [0x00003e70] [2019-03-01 19:09:35,530] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [0x00003e70] [2019-03-01 19:09:35,531] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003e70] [2019-03-01 19:09:35,531] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00003e70] [2019-03-01 19:09:35,719] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00003e70] [2019-03-01 19:09:35,719] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003e70] [2019-03-01 19:09:35,836] - loaded entity-script:Account(1).
  WARN root [0x00003e70] [2019-03-01 19:09:35,837] - EntityDef::checkDefMethod: exposed of method: Room.enterGameWorld, check the caller can use "def enterGameWorld(self, callerID, ...)", such as: if callerID == self.id!
 DEBUG root [0x00003e70] [2019-03-01 19:09:35,837] - loaded entity-script:Room(3).
  INFO root [0x00003e70] [2019-03-01 19:09:35,838] - TelnetServer server is running on port 50000
  INFO root [0x00003e70] [2019-03-01 19:09:36,311] - ---- cellapp is running ----
 DEBUG root [0x00003e70] [2019-03-01 19:09:36,312] - Components::process(): Request for the process of identity...
  WARN root [0x00003e70] [2019-03-01 19:09:42,477] - EntityApp::checkTickPeriod: tick took 6165% (6.16 seconds)!
  INFO root [0x00003e70] [2019-03-01 19:09:43,512] - Components::findComponents: find logger(1)...
  WARN root [0x00003e70] [2019-03-01 19:09:43,850] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20624, errorno=10048
  WARN root [0x00003e70] [2019-03-01 19:09:43,850] - EntityApp::checkTickPeriod: tick took 438% (0.44 seconds)!
  INFO root [0x00003e70] [2019-03-01 19:09:44,876] - Components::findComponents: find logger(2)...
  INFO root [0x00003e70] [2019-03-01 19:09:44,911] - Components::findComponents: found logger, addr:192.168.0.148:11082
  INFO root [0x00003e70] [2019-03-01 19:09:44,913] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00003e70] [2019-03-01 19:09:44,914] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003e70] [2019-03-01 19:09:44,917] - Components::findComponents: find dbmgr(3)...
  INFO root [0x00003e70] [2019-03-01 19:09:45,023] - Components::findComponents: found dbmgr, addr:192.168.0.148:11076
  INFO root [0x00003e70] [2019-03-01 19:09:45,023] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [0x00003e70] [2019-03-01 19:09:45,023] - Components::addComponent[dbmgr], uid=28936, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003e70] [2019-03-01 19:09:45,024] - Components::findComponents: found dbmgr, addr:192.168.0.148:11076
  WARN root [0x00003e70] [2019-03-01 19:09:46,024] - Forwarding logs to logger[192.168.0.148:11082/0/0/0]...
 ERROR root [0x00003e70] [2019-03-01 19:22:37,338] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00003e70] [2019-03-01 19:22:37,341] - The following logs sent to logger failed:
  WARN root [0x00003e70] [2019-03-01 19:22:37,341] - ==> [2019-03-01 19:22:37 339] TCPPacketReceiver::processPendingEvents(192.168.0.148:11082): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003e70] [2019-03-01 19:22:37,341] - ==> [2019-03-01 19:22:37 340] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [0x00003e70] [2019-03-01 19:22:37,377] - TCPPacketReceiver::processPendingEvents(192.168.0.148:11076): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003e70] [2019-03-01 19:22:37,387] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [0x00003e70] [2019-03-01 19:22:37,387] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00003e70] [2019-03-01 19:22:37,387] - Shutdowner::onShutdown: shutting down
 S_DBG root [0x00003e70] [2019-03-01 19:22:37,387] - Avatar::onDestroy: 2.
 S_ERR root [0x00003e70] [2019-03-01 19:22:37,387] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x00003e70] [2019-03-01 19:22:37,387] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
 S_DBG root [0x00003e70] [2019-03-01 19:22:37,387] - Avatar::onDestroy: 4.
 S_ERR root [0x00003e70] [2019-03-01 19:22:37,397] - Traceback (most recent call last):
  File "D:/kbengine-2.4.2/first_server_assets/scripts/cell\Account.py", line 18, in onDestroy
    room = self.getCurrRoom()
 S_ERR root [0x00003e70] [2019-03-01 19:22:37,397] - AttributeError: 'Account' object has no attribute 'getCurrRoom'
  INFO root [0x00003e70] [2019-03-01 19:22:37,397] - Spaces::destroySpace: 1.
  INFO root [0x00003e70] [2019-03-01 19:22:37,397] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00003e70] [2019-03-01 19:22:37,397] - Room::~Room(): 3
 DEBUG root [0x00003e70] [2019-03-01 19:22:37,397] - Account::~Account(): 2
 DEBUG root [0x00003e70] [2019-03-01 19:22:37,397] - Account::~Account(): 4
 DEBUG root [0x00003e70] [2019-03-01 19:22:37,397] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x00003e70] [2019-03-01 19:22:37,397] - Witness::destroyObjPool(): size 16.
 ERROR root [0x00003e70] [2019-03-01 19:22:37,408] - PyGC::debugTracing(): Vector3 : leaked(1)
  INFO root [0x00003e70] [2019-03-01 19:22:37,421] - Script::uninstall(): is successfully!
 DEBUG root [0x00003e70] [2019-03-01 19:22:37,421] - ThreadPool::destroy(): starting size 2.
