  INFO root [2019-03-02 09:58:38,026] - 
  INFO root [2019-03-02 09:58:38,026] - -----------------------------------------------------------------------------------------


  INFO root [2019-03-02 09:58:38,026] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [2019-03-02 09:58:38,042] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [2019-03-02 10:02:43,260] - 
  INFO root [2019-03-02 10:02:43,260] - -----------------------------------------------------------------------------------------


  INFO root [2019-03-02 10:02:43,275] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [2019-03-02 10:02:43,275] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [2019-03-02 10:02:43,275] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [2019-03-02 10:02:43,275] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20013 )
  INFO root [2019-03-02 10:02:43,275] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.0.148:20013, SOMAXCONN=128.
  INFO root [2019-03-02 10:02:43,275] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:1737 )
  INFO root [2019-03-02 10:02:43,275] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:1737, SOMAXCONN=128.
  INFO root [2019-03-02 10:02:43,275] - server-configs:
  INFO root [2019-03-02 10:02:43,275] - 	internalTcpAddr : 192.168.0.148:1737
  INFO root [2019-03-02 10:02:43,275] - 	externalTcpAddr : 192.168.0.148:20013
  INFO root [2019-03-02 10:02:43,275] - 	componentID : 9000
  WARN root [2019-03-02 10:02:43,541] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  WARN root [2019-03-02 10:02:44,025] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20537, errorno=10048
  INFO root [2019-03-02 10:02:44,025] - ---- loginapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: 7DB67FD8A6CA6099F26F40C54BC962E0. Config: Debug X86. Built: 17:20:28 Feb 27 2019. AppID: 9000. UID: 28936. PID: 11796 ----
  INFO root [2019-03-02 10:02:44,025] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [2019-03-02 10:02:44,041] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-03-02 10:02:44,041] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-03-02 10:02:44,275] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-03-02 10:02:44,275] - Script::install(): KBExtra is successfully!
S_INFO root [2019-03-02 10:02:44,275] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-03-02 10:02:44,275] - TelnetServer server is running on port 31000
  INFO root [2019-03-02 10:02:44,556] - ---- loginapp is running ----
 DEBUG root [2019-03-02 10:02:44,556] - Components::process(): Request for the process of identity...
  INFO root [2019-03-02 10:02:51,902] - Components::findComponents: find logger(1)...
  WARN root [2019-03-02 10:02:53,027] - Components::findComponents: not found logger!
  INFO root [2019-03-02 10:02:54,042] - Components::findComponents: find dbmgr(1)...
  WARN root [2019-03-02 10:02:54,527] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20058, errorno=10048
  INFO root [2019-03-02 10:02:55,542] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-03-02 10:02:57,651] - Components::findComponents: find dbmgr(3)...
  INFO root [2019-03-02 10:02:59,729] - Components::findComponents: find dbmgr(4)...
  INFO root [2019-03-02 10:03:01,807] - Components::findComponents: find dbmgr(5)...
  INFO root [2019-03-02 10:03:03,885] - Components::findComponents: find dbmgr(6)...
  INFO root [2019-03-02 10:03:05,979] - Components::findComponents: find dbmgr(7)...
  INFO root [2019-03-02 10:03:08,029] - Components::findComponents: find dbmgr(8)...
  INFO root [2019-03-02 10:03:10,122] - Components::findComponents: find dbmgr(9)...
  INFO root [2019-03-02 10:03:12,200] - Components::findComponents: find dbmgr(10)...
  INFO root [2019-03-02 10:03:14,278] - Components::findComponents: find dbmgr(11)...
  INFO root [2019-03-02 10:03:16,356] - Components::findComponents: find dbmgr(12)...
  INFO root [2019-03-02 10:03:18,434] - Components::findComponents: find dbmgr(13)...
  INFO root [2019-03-02 10:03:39,058] - 
  INFO root [2019-03-02 10:03:39,058] - -----------------------------------------------------------------------------------------


  INFO root [2019-03-02 10:03:39,058] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [2019-03-02 10:03:39,058] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [2019-03-02 10:03:39,058] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [2019-03-02 10:03:39,073] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20013 )
  INFO root [2019-03-02 10:03:39,073] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.0.148:20013, SOMAXCONN=128.
  INFO root [2019-03-02 10:03:39,073] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:1765 )
  INFO root [2019-03-02 10:03:39,073] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:1765, SOMAXCONN=128.
  INFO root [2019-03-02 10:03:39,073] - server-configs:
  INFO root [2019-03-02 10:03:39,073] - 	internalTcpAddr : 192.168.0.148:1765
  INFO root [2019-03-02 10:03:39,073] - 	externalTcpAddr : 192.168.0.148:20013
  INFO root [2019-03-02 10:03:39,073] - 	componentID : 9000
  WARN root [2019-03-02 10:03:39,417] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [2019-03-02 10:03:39,683] - Components::findLogger: found logger, addr:192.168.0.148:1763
  INFO root [2019-03-02 10:03:39,683] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [2019-03-02 10:03:39,683] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-03-02 10:03:39,683] - ---- loginapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: 7DB67FD8A6CA6099F26F40C54BC962E0. Config: Debug X86. Built: 17:20:28 Feb 27 2019. AppID: 9000. UID: 28936. PID: 11544 ----
  INFO root [2019-03-02 10:03:39,698] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [2019-03-02 10:03:39,698] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-03-02 10:03:39,698] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-03-02 10:03:39,886] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-03-02 10:03:39,886] - Script::install(): KBExtra is successfully!
S_INFO root [2019-03-02 10:03:39,901] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-03-02 10:03:39,901] - TelnetServer server is running on port 31000
  INFO root [2019-03-02 10:03:40,292] - ---- loginapp is running ----
 DEBUG root [2019-03-02 10:03:40,292] - Components::process(): Request for the process of identity...
  WARN root [2019-03-02 10:03:46,588] - Forwarding logs to logger[192.168.0.148:1763/0/0/0]...
 ERROR root [2019-03-02 10:05:57,967] - 192.168.0.141:49271: TCPPacketSender::processSend(internal, 1): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [2019-03-02 10:06:00,885] - 6 reports of '192.168.0.141:49271: TCPPacketSender::processSend(internal, 1): Exception occurred: REASON_RESOURCE_UNAVAILABLE' in the last 2926ms
 ERROR root [2019-03-02 10:06:02,138] - 192.168.0.141:49271: TCPPacketSender::processSend(internal, 2): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [2019-03-02 10:06:03,080] - 35 reports of '192.168.0.141:49271: TCPPacketSender::processSend(internal, 1): Exception occurred: REASON_RESOURCE_UNAVAILABLE' in the last 2188ms
 ERROR root [2019-03-02 10:06:04,949] - 2 reports of '192.168.0.141:49271: TCPPacketSender::processSend(internal, 2): Exception occurred: REASON_RESOURCE_UNAVAILABLE' in the last 2809ms
 ERROR root [2019-03-02 10:06:05,074] - 30 reports of '192.168.0.141:49271: TCPPacketSender::processSend(internal, 1): Exception occurred: REASON_RESOURCE_UNAVAILABLE' in the last 2001ms
 ERROR root [2019-03-02 10:06:07,083] - 25 reports of '192.168.0.141:49271: TCPPacketSender::processSend(internal, 1): Exception occurred: REASON_RESOURCE_UNAVAILABLE' in the last 2001ms
 ERROR root [2019-03-02 10:06:07,083] - 2 reports of '192.168.0.141:49271: TCPPacketSender::processSend(internal, 2): Exception occurred: REASON_RESOURCE_UNAVAILABLE' in the last 2128ms
 ERROR root [2019-03-02 10:06:09,264] - 40 reports of '192.168.0.141:49271: TCPPacketSender::processSend(internal, 1): Exception occurred: REASON_RESOURCE_UNAVAILABLE' in the last 2184ms
 ERROR root [2019-03-02 10:06:10,234] - 1 reports of '192.168.0.141:49271: TCPPacketSender::processSend(internal, 2): Exception occurred: REASON_RESOURCE_UNAVAILABLE' in the last 3152ms
 ERROR root [2019-03-02 10:06:13,074] - 32 reports of '192.168.0.141:49271: TCPPacketSender::processSend(internal, 1): Exception occurred: REASON_RESOURCE_UNAVAILABLE' in the last 3807ms
 ERROR root [2019-03-02 10:09:01,283] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [2019-03-02 10:09:01,305] - The following logs sent to logger failed:
  WARN root [2019-03-02 10:09:01,306] - ==> [2019-03-02 10:09:01 265] TCPPacketReceiver::processPendingEvents(192.168.0.148:1763): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-03-02 10:09:01,306] - ==> [2019-03-02 10:09:01 284] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [2019-03-02 10:09:01,307] - TCPPacketReceiver::processPendingEvents(192.168.0.148:1768): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-03-02 10:09:01,308] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [2019-03-02 10:09:01,325] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-03-02 10:09:01,325] - onLoginAppShutDown()
  INFO root [2019-03-02 10:09:01,325] - Shutdowner::onShutdown: shutting down
  INFO root [2019-03-02 10:09:01,325] - Shutdowner::onShutdownEnd: shutting down
  WARN root [2019-03-02 10:09:01,325] - TCPPacketReceiver::processPendingEvents(192.168.0.148:1766): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
  INFO root [2019-03-02 10:09:01,326] - Components::removeComponentByChannel: baseappmgr : 5000, Normal exit!
  INFO root [2019-03-02 10:09:01,331] - Script::uninstall(): is successfully!
 DEBUG root [2019-03-02 10:09:01,331] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-03-02 10:09:01,632] - ThreadPool::destroy(): waiting for thread(2)[0x1c3ac70,0x1c3ada8,], try=1
 DEBUG root [2019-03-02 10:09:02,033] - TPThread::~TPThread(): 0x1c3ac70
 DEBUG root [2019-03-02 10:09:02,033] - TPThread::~TPThread(): 0x1c3ada8
 DEBUG root [2019-03-02 10:09:02,033] - ThreadPool::destroy(): successfully!
 DEBUG root [2019-03-02 10:09:02,070] - Bundle::destroyObjPool(): size 258.
 DEBUG root [2019-03-02 10:09:02,071] - Channel::destroyObjPool(): size 16.
 DEBUG root [2019-03-02 10:09:02,072] - TCPPacket::destroyObjPool(): size 465.
 DEBUG root [2019-03-02 10:09:02,073] - UDPPacket::destroyObjPool(): size 1.
 DEBUG root [2019-03-02 10:09:02,073] - EndPoint::destroyObjPool(): size 15.
 DEBUG root [2019-03-02 10:09:02,073] - Address::destroyObjPool(): size 0.
 DEBUG root [2019-03-02 10:09:02,073] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2019-03-02 10:09:02,074] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2019-03-02 10:09:02,074] - loginapp(9000) has shut down.
  INFO root [2019-03-02 10:09:03,075] - EventDispatcher()::~EventDispatcher: Num timers = 1
  INFO root [2019-03-02 10:10:53,308] - 
  INFO root [2019-03-02 10:10:53,320] - -----------------------------------------------------------------------------------------


  INFO root [2019-03-02 10:10:53,320] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [2019-03-02 10:10:53,320] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [2019-03-02 10:10:53,320] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [2019-03-02 10:10:53,320] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.123 ( 192.168.0.123:20013 )
  INFO root [2019-03-02 10:10:53,320] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.0.123:20013, SOMAXCONN=128.
  INFO root [2019-03-02 10:10:53,320] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.123 ( 192.168.0.123:2727 )
  INFO root [2019-03-02 10:10:53,320] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.123:2727, SOMAXCONN=128.
  INFO root [2019-03-02 10:10:53,320] - server-configs:
  INFO root [2019-03-02 10:10:53,320] - 	internalTcpAddr : 192.168.0.123:2727
  INFO root [2019-03-02 10:10:53,320] - 	externalTcpAddr : 192.168.0.123:20013
  INFO root [2019-03-02 10:10:53,320] - 	componentID : 9000
  WARN root [2019-03-02 10:10:53,549] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [2019-03-02 10:10:53,589] - Components::findLogger: found logger, addr:192.168.0.123:2683
  INFO root [2019-03-02 10:10:53,589] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [2019-03-02 10:10:53,589] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-03-02 10:10:53,589] - ---- loginapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: 7DB67FD8A6CA6099F26F40C54BC962E0. Config: Debug X86. Built: 17:20:28 Feb 27 2019. AppID: 9000. UID: 28936. PID: 11564 ----
  INFO root [2019-03-02 10:10:53,589] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [2019-03-02 10:10:53,589] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-03-02 10:10:53,589] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-03-02 10:10:53,763] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-03-02 10:10:53,763] - Script::install(): KBExtra is successfully!
S_INFO root [2019-03-02 10:10:53,780] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-03-02 10:10:53,780] - TelnetServer server is running on port 31000
  INFO root [2019-03-02 10:10:54,060] - ---- loginapp is running ----
 DEBUG root [2019-03-02 10:10:54,060] - Components::process(): Request for the process of identity...
  WARN root [2019-03-02 10:11:00,310] - Forwarding logs to logger[192.168.0.123:2683/0/0/0]...
 ERROR root [2019-03-02 10:13:34,081] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [2019-03-02 10:13:34,081] - The following logs sent to logger failed:
  WARN root [2019-03-02 10:13:34,081] - ==> [2019-03-02 10:13:34 086] TCPPacketReceiver::processPendingEvents(192.168.0.123:2683): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-03-02 10:13:34,081] - ==> [2019-03-02 10:13:34 086] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [2019-03-02 10:13:34,139] - TCPPacketReceiver::processPendingEvents(192.168.0.123:2685): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-03-02 10:13:34,139] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [2019-03-02 10:13:34,149] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-03-02 10:13:34,149] - onLoginAppShutDown()
  INFO root [2019-03-02 10:13:34,149] - Shutdowner::onShutdown: shutting down
  INFO root [2019-03-02 10:13:34,149] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-03-02 10:13:34,159] - Script::uninstall(): is successfully!
 DEBUG root [2019-03-02 10:13:34,159] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-03-02 10:16:41,242] - 
  INFO root [2019-03-02 10:16:41,242] - -----------------------------------------------------------------------------------------


  INFO root [2019-03-02 10:16:41,249] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [2019-03-02 10:16:41,249] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [2019-03-02 10:16:41,249] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [2019-03-02 10:16:41,252] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.123 ( 192.168.0.123:20013 )
  INFO root [2019-03-02 10:16:41,252] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.0.123:20013, SOMAXCONN=128.
  INFO root [2019-03-02 10:16:41,259] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.123 ( 192.168.0.123:2853 )
  INFO root [2019-03-02 10:16:41,259] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.123:2853, SOMAXCONN=128.
  INFO root [2019-03-02 10:16:41,259] - server-configs:
  INFO root [2019-03-02 10:16:41,259] - 	internalTcpAddr : 192.168.0.123:2853
  INFO root [2019-03-02 10:16:41,259] - 	externalTcpAddr : 192.168.0.123:20013
  INFO root [2019-03-02 10:16:41,259] - 	componentID : 9000
  WARN root [2019-03-02 10:16:41,559] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [2019-03-02 10:16:41,803] - Components::findLogger: found logger, addr:192.168.0.123:2851
  INFO root [2019-03-02 10:16:41,803] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [2019-03-02 10:16:41,803] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-03-02 10:16:41,803] - ---- loginapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: 7DB67FD8A6CA6099F26F40C54BC962E0. Config: Debug X86. Built: 17:20:28 Feb 27 2019. AppID: 9000. UID: 28936. PID: 2384 ----
  INFO root [2019-03-02 10:16:41,803] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [2019-03-02 10:16:41,809] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-03-02 10:16:41,809] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-03-02 10:16:41,990] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-03-02 10:16:41,990] - Script::install(): KBExtra is successfully!
S_INFO root [2019-03-02 10:16:41,997] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-03-02 10:16:41,997] - TelnetServer server is running on port 31000
  INFO root [2019-03-02 10:16:42,329] - ---- loginapp is running ----
 DEBUG root [2019-03-02 10:16:42,329] - Components::process(): Request for the process of identity...
  WARN root [2019-03-02 10:16:48,513] - Forwarding logs to logger[192.168.0.123:2851/0/0/0]...
 ERROR root [2019-03-02 10:17:07,851] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [2019-03-02 10:17:07,851] - The following logs sent to logger failed:
  WARN root [2019-03-02 10:17:07,851] - ==> [2019-03-02 10:17:07 854] TCPPacketReceiver::processPendingEvents(192.168.0.123:2851): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-03-02 10:17:07,851] - ==> [2019-03-02 10:17:07 855] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [2019-03-02 10:17:07,878] - TCPPacketReceiver::processPendingEvents(192.168.0.123:2850): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-03-02 10:17:07,878] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [2019-03-02 10:17:07,878] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-03-02 10:17:07,878] - onLoginAppShutDown()
  INFO root [2019-03-02 10:17:07,878] - Shutdowner::onShutdown: shutting down
  INFO root [2019-03-02 10:17:07,878] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-03-02 10:17:07,888] - Script::uninstall(): is successfully!
 DEBUG root [2019-03-02 10:17:07,888] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-03-02 10:17:15,739] - 
  INFO root [2019-03-02 10:17:15,739] - -----------------------------------------------------------------------------------------


  INFO root [2019-03-02 10:17:15,739] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [2019-03-02 10:17:15,739] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [2019-03-02 10:17:15,739] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [2019-03-02 10:17:15,750] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.123 ( 192.168.0.123:20013 )
  INFO root [2019-03-02 10:17:15,750] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.0.123:20013, SOMAXCONN=128.
  INFO root [2019-03-02 10:17:15,750] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.123 ( 192.168.0.123:2904 )
  INFO root [2019-03-02 10:17:15,750] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.123:2904, SOMAXCONN=128.
  INFO root [2019-03-02 10:17:15,750] - server-configs:
  INFO root [2019-03-02 10:17:15,750] - 	internalTcpAddr : 192.168.0.123:2904
  INFO root [2019-03-02 10:17:15,750] - 	externalTcpAddr : 192.168.0.123:20013
  INFO root [2019-03-02 10:17:15,750] - 	componentID : 9000
  WARN root [2019-03-02 10:17:16,090] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [2019-03-02 10:17:16,298] - Components::findLogger: found logger, addr:192.168.0.123:2899
  INFO root [2019-03-02 10:17:16,298] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [2019-03-02 10:17:16,298] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-03-02 10:17:16,298] - ---- loginapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: 7DB67FD8A6CA6099F26F40C54BC962E0. Config: Debug X86. Built: 17:20:28 Feb 27 2019. AppID: 9000. UID: 28936. PID: 6232 ----
  INFO root [2019-03-02 10:17:16,298] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [2019-03-02 10:17:16,298] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-03-02 10:17:16,298] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-03-02 10:17:16,529] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-03-02 10:17:16,529] - Script::install(): KBExtra is successfully!
S_INFO root [2019-03-02 10:17:16,542] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-03-02 10:17:16,549] - TelnetServer server is running on port 31000
  INFO root [2019-03-02 10:17:16,908] - ---- loginapp is running ----
 DEBUG root [2019-03-02 10:17:16,908] - Components::process(): Request for the process of identity...
  WARN root [2019-03-02 10:17:23,051] - Forwarding logs to logger[192.168.0.123:2899/0/0/0]...
 ERROR root [2019-03-02 10:18:33,693] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [2019-03-02 10:18:33,695] - The following logs sent to logger failed:
  WARN root [2019-03-02 10:18:33,695] - ==> [2019-03-02 10:18:33 694] TCPPacketReceiver::processPendingEvents(192.168.0.123:2899): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-03-02 10:18:33,695] - ==> [2019-03-02 10:18:33 694] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [2019-03-02 10:18:33,731] - TCPPacketReceiver::processPendingEvents(192.168.0.123:2902): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-03-02 10:18:33,733] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [2019-03-02 10:18:33,739] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-03-02 10:18:33,743] - onLoginAppShutDown()
  INFO root [2019-03-02 10:18:33,743] - Shutdowner::onShutdown: shutting down
  INFO root [2019-03-02 10:18:33,743] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-03-02 10:18:33,753] - Script::uninstall(): is successfully!
 DEBUG root [2019-03-02 10:18:33,754] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-03-02 10:20:36,632] - 
  INFO root [2019-03-02 10:20:36,632] - -----------------------------------------------------------------------------------------


  INFO root [2019-03-02 10:20:36,638] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [2019-03-02 10:20:36,638] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [2019-03-02 10:20:36,638] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [2019-03-02 10:20:36,638] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.123 ( 192.168.0.123:20013 )
  INFO root [2019-03-02 10:20:36,638] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.0.123:20013, SOMAXCONN=128.
  INFO root [2019-03-02 10:20:36,648] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.123 ( 192.168.0.123:2996 )
  INFO root [2019-03-02 10:20:36,648] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.123:2996, SOMAXCONN=128.
  INFO root [2019-03-02 10:20:36,648] - server-configs:
  INFO root [2019-03-02 10:20:36,648] - 	internalTcpAddr : 192.168.0.123:2996
  INFO root [2019-03-02 10:20:36,648] - 	externalTcpAddr : 192.168.0.123:20013
  INFO root [2019-03-02 10:20:36,648] - 	componentID : 9000
  WARN root [2019-03-02 10:20:36,887] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [2019-03-02 10:20:37,141] - Components::findLogger: found logger, addr:192.168.0.123:2993
  INFO root [2019-03-02 10:20:37,141] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [2019-03-02 10:20:37,141] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-03-02 10:20:37,149] - ---- loginapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: 7DB67FD8A6CA6099F26F40C54BC962E0. Config: Debug X86. Built: 17:20:28 Feb 27 2019. AppID: 9000. UID: 28936. PID: 2628 ----
  INFO root [2019-03-02 10:20:37,149] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [2019-03-02 10:20:37,151] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-03-02 10:20:37,151] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-03-02 10:20:37,328] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-03-02 10:20:37,328] - Script::install(): KBExtra is successfully!
S_INFO root [2019-03-02 10:20:37,332] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-03-02 10:20:37,332] - TelnetServer server is running on port 31000
  INFO root [2019-03-02 10:20:37,738] - ---- loginapp is running ----
 DEBUG root [2019-03-02 10:20:37,738] - Components::process(): Request for the process of identity...
  WARN root [2019-03-02 10:20:43,968] - Forwarding logs to logger[192.168.0.123:2993/0/0/0]...
 ERROR root [2019-03-02 10:27:41,787] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [2019-03-02 10:27:41,787] - The following logs sent to logger failed:
  WARN root [2019-03-02 10:27:41,787] - ==> [2019-03-02 10:27:41 794] TCPPacketReceiver::processPendingEvents(192.168.0.123:2993): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-03-02 10:27:41,787] - ==> [2019-03-02 10:27:41 794] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [2019-03-02 10:27:41,817] - TCPPacketReceiver::processPendingEvents(192.168.0.123:2988): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-03-02 10:27:41,817] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [2019-03-02 10:27:41,827] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-03-02 10:27:41,827] - onLoginAppShutDown()
  INFO root [2019-03-02 10:27:41,827] - Shutdowner::onShutdown: shutting down
  INFO root [2019-03-02 10:27:41,827] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-03-02 10:27:41,837] - Script::uninstall(): is successfully!
 DEBUG root [2019-03-02 10:27:41,837] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-03-02 10:35:36,390] - 
  INFO root [2019-03-02 10:35:36,390] - -----------------------------------------------------------------------------------------


  INFO root [2019-03-02 10:35:36,390] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [2019-03-02 10:35:36,390] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [2019-03-02 10:35:36,396] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [2019-03-02 10:35:36,399] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.123 ( 192.168.0.123:20013 )
  INFO root [2019-03-02 10:35:36,399] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.0.123:20013, SOMAXCONN=128.
  INFO root [2019-03-02 10:35:36,399] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.123 ( 192.168.0.123:3248 )
  INFO root [2019-03-02 10:35:36,399] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.123:3248, SOMAXCONN=128.
  INFO root [2019-03-02 10:35:36,399] - server-configs:
  INFO root [2019-03-02 10:35:36,399] - 	internalTcpAddr : 192.168.0.123:3248
  INFO root [2019-03-02 10:35:36,399] - 	externalTcpAddr : 192.168.0.123:20013
  INFO root [2019-03-02 10:35:36,399] - 	componentID : 9000
  WARN root [2019-03-02 10:35:36,739] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [2019-03-02 10:35:36,989] - Components::findLogger: found logger, addr:192.168.0.123:3254
  INFO root [2019-03-02 10:35:36,989] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [2019-03-02 10:35:36,989] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-03-02 10:35:36,995] - ---- loginapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: 7DB67FD8A6CA6099F26F40C54BC962E0. Config: Debug X86. Built: 17:20:28 Feb 27 2019. AppID: 9000. UID: 28936. PID: 13128 ----
  INFO root [2019-03-02 10:35:36,995] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [2019-03-02 10:35:36,995] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-03-02 10:35:36,995] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-03-02 10:35:37,167] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-03-02 10:35:37,169] - Script::install(): KBExtra is successfully!
S_INFO root [2019-03-02 10:35:37,178] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-03-02 10:35:37,178] - TelnetServer server is running on port 31000
  INFO root [2019-03-02 10:35:37,585] - ---- loginapp is running ----
 DEBUG root [2019-03-02 10:35:37,586] - Components::process(): Request for the process of identity...
  WARN root [2019-03-02 10:35:43,826] - Forwarding logs to logger[192.168.0.123:3254/0/0/0]...
 ERROR root [2019-03-02 10:46:59,094] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [2019-03-02 10:46:59,094] - The following logs sent to logger failed:
  WARN root [2019-03-02 10:46:59,094] - ==> [2019-03-02 10:46:59 099] TCPPacketReceiver::processPendingEvents(192.168.0.123:3254): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-03-02 10:46:59,094] - ==> [2019-03-02 10:46:59 100] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [2019-03-02 10:46:59,144] - TCPPacketReceiver::processPendingEvents(192.168.0.123:3251): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-03-02 10:46:59,144] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [2019-03-02 10:46:59,144] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-03-02 10:46:59,144] - onLoginAppShutDown()
  INFO root [2019-03-02 10:46:59,144] - Shutdowner::onShutdown: shutting down
  INFO root [2019-03-02 10:46:59,144] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-03-02 10:46:59,165] - Script::uninstall(): is successfully!
 DEBUG root [2019-03-02 10:46:59,165] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-03-02 10:48:41,817] - 
  INFO root [2019-03-02 10:48:41,817] - -----------------------------------------------------------------------------------------


  INFO root [2019-03-02 10:48:41,825] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [2019-03-02 10:48:41,825] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [2019-03-02 10:48:41,825] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [2019-03-02 10:48:41,825] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.123 ( 192.168.0.123:20013 )
  INFO root [2019-03-02 10:48:41,825] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.0.123:20013, SOMAXCONN=128.
  INFO root [2019-03-02 10:48:41,825] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.123 ( 192.168.0.123:3605 )
  INFO root [2019-03-02 10:48:41,834] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.123:3605, SOMAXCONN=128.
  INFO root [2019-03-02 10:48:41,834] - server-configs:
  INFO root [2019-03-02 10:48:41,834] - 	internalTcpAddr : 192.168.0.123:3605
  INFO root [2019-03-02 10:48:41,834] - 	externalTcpAddr : 192.168.0.123:20013
  INFO root [2019-03-02 10:48:41,834] - 	componentID : 9000
  WARN root [2019-03-02 10:48:42,138] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [2019-03-02 10:48:42,304] - Components::findLogger: found logger, addr:192.168.0.123:3603
  INFO root [2019-03-02 10:48:42,304] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [2019-03-02 10:48:42,304] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-03-02 10:48:42,314] - ---- loginapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: 7DB67FD8A6CA6099F26F40C54BC962E0. Config: Debug X86. Built: 17:20:28 Feb 27 2019. AppID: 9000. UID: 28936. PID: 6520 ----
  INFO root [2019-03-02 10:48:42,314] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [2019-03-02 10:48:42,314] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-03-02 10:48:42,314] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-03-02 10:48:42,494] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-03-02 10:48:42,494] - Script::install(): KBExtra is successfully!
S_INFO root [2019-03-02 10:48:42,504] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-03-02 10:48:42,504] - TelnetServer server is running on port 31000
  INFO root [2019-03-02 10:48:42,844] - ---- loginapp is running ----
 DEBUG root [2019-03-02 10:48:42,844] - Components::process(): Request for the process of identity...
  WARN root [2019-03-02 10:48:49,014] - Forwarding logs to logger[192.168.0.123:3603/0/0/0]...
 ERROR root [2019-03-02 11:24:21,591] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [2019-03-02 11:24:21,624] - The following logs sent to logger failed:
  WARN root [2019-03-02 11:24:21,624] - ==> [2019-03-02 11:24:21 571] TCPPacketReceiver::processPendingEvents(192.168.0.123:3603): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-03-02 11:24:21,624] - ==> [2019-03-02 11:24:21 592] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [2019-03-02 11:24:21,648] - TCPPacketReceiver::processPendingEvents(192.168.0.123:3606): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-03-02 11:24:21,673] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [2019-03-02 11:24:21,682] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-03-02 11:24:21,686] - onLoginAppShutDown()
  INFO root [2019-03-02 11:24:21,686] - Shutdowner::onShutdown: shutting down
  INFO root [2019-03-02 11:24:21,686] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-03-02 11:24:21,698] - Script::uninstall(): is successfully!
 DEBUG root [2019-03-02 11:24:21,699] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-03-02 11:24:22,000] - ThreadPool::destroy(): waiting for thread(2)[0x1cf9840,0x1cf9088,], try=1
  INFO root [2019-03-02 14:45:13,599] - 
  INFO root [2019-03-02 14:45:13,611] - -----------------------------------------------------------------------------------------


  INFO root [2019-03-02 14:45:13,649] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [2019-03-02 14:45:13,649] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [2019-03-02 14:45:13,649] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [2019-03-02 14:45:13,731] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20013 )
  INFO root [2019-03-02 14:45:13,731] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.0.148:20013, SOMAXCONN=128.
  INFO root [2019-03-02 14:45:13,735] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:13815 )
  INFO root [2019-03-02 14:45:13,736] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:13815, SOMAXCONN=128.
  INFO root [2019-03-02 14:45:13,736] - server-configs:
  INFO root [2019-03-02 14:45:13,736] - 	internalTcpAddr : 192.168.0.148:13815
  INFO root [2019-03-02 14:45:13,736] - 	externalTcpAddr : 192.168.0.148:20013
  INFO root [2019-03-02 14:45:13,736] - 	componentID : 9000
  WARN root [2019-03-02 14:45:14,105] - invalid UID(0) <= 0, please check UID for environment! automatically set to 28936.
  INFO root [2019-03-02 14:45:14,139] - Components::findLogger: found logger, addr:192.168.0.148:13513
  INFO root [2019-03-02 14:45:14,140] - Components::addComponent: reset orderLog, uid=28936!
  INFO root [2019-03-02 14:45:14,140] - Components::addComponent[logger], uid=28936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-03-02 14:45:14,159] - ---- loginapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: 7DB67FD8A6CA6099F26F40C54BC962E0. Config: Debug X86. Built: 17:20:28 Feb 27 2019. AppID: 9000. UID: 28936. PID: 15944 ----
  INFO root [2019-03-02 14:45:14,159] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [2019-03-02 14:45:14,190] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-03-02 14:45:14,204] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-03-02 14:45:14,414] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-03-02 14:45:14,414] - Script::install(): KBExtra is successfully!
S_INFO root [2019-03-02 14:45:14,455] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-03-02 14:45:14,456] - TelnetServer server is running on port 31000
  INFO root [2019-03-02 14:45:15,070] - ---- loginapp is running ----
 DEBUG root [2019-03-02 14:45:15,071] - Components::process(): Request for the process of identity...
  WARN root [2019-03-02 14:45:21,304] - Forwarding logs to logger[192.168.0.148:13513/0/0/0]...
 ERROR root [2019-03-02 14:45:30,897] - Components::removeComponentByChannel: baseappmgr : 5000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

 ERROR root [2019-03-02 14:45:30,902] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [2019-03-02 14:45:30,905] - The following logs sent to logger failed:
  WARN root [2019-03-02 14:45:30,906] - ==> [2019-03-02 14:45:30 856] TCPPacketReceiver::processPendingEvents(192.168.0.148:13606): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-03-02 14:45:30,906] - ==> [2019-03-02 14:45:30 898] Components::removeComponentByChannel: baseappmgr : 5000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [2019-03-02 14:45:30,906] - ==> [2019-03-02 14:45:30 902] TCPPacketReceiver::processPendingEvents(192.168.0.148:13513): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-03-02 14:45:30,906] - ==> [2019-03-02 14:45:30 903] Components::removeComponentByChannel: logger : 2000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  WARN root [2019-03-02 14:45:30,907] - TCPPacketReceiver::processPendingEvents(192.168.0.148:13566): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-03-02 14:45:30,907] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

  INFO root [2019-03-02 14:45:30,930] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-03-02 14:45:30,931] - onLoginAppShutDown()
  INFO root [2019-03-02 14:45:30,931] - Shutdowner::onShutdown: shutting down
  INFO root [2019-03-02 14:45:30,931] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-03-02 14:45:30,974] - Script::uninstall(): is successfully!
 DEBUG root [2019-03-02 14:45:30,974] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-03-02 14:45:31,276] - ThreadPool::destroy(): waiting for thread(2)[0xafbc60,0xafb4a8,], try=1
 DEBUG root [2019-03-02 14:45:31,677] - TPThread::~TPThread(): 0xafbc60
 DEBUG root [2019-03-02 14:45:31,677] - TPThread::~TPThread(): 0xafb4a8
 DEBUG root [2019-03-02 14:45:31,677] - ThreadPool::destroy(): successfully!
 DEBUG root [2019-03-02 14:45:31,709] - Bundle::destroyObjPool(): size 20.
 DEBUG root [2019-03-02 14:45:31,710] - Channel::destroyObjPool(): size 16.
 DEBUG root [2019-03-02 14:45:31,710] - TCPPacket::destroyObjPool(): size 3.
 DEBUG root [2019-03-02 14:45:31,710] - UDPPacket::destroyObjPool(): size 2.
 DEBUG root [2019-03-02 14:45:31,710] - EndPoint::destroyObjPool(): size 15.
 DEBUG root [2019-03-02 14:45:31,711] - Address::destroyObjPool(): size 0.
 DEBUG root [2019-03-02 14:45:31,711] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2019-03-02 14:45:31,711] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2019-03-02 14:45:31,711] - loginapp(9000) has shut down.
  INFO root [2019-03-02 14:45:32,763] - EventDispatcher()::~EventDispatcher: Num timers = 1
  INFO root [2019-03-02 14:45:57,887] - 
  INFO root [2019-03-02 14:45:57,900] - -----------------------------------------------------------------------------------------


  INFO root [2019-03-02 14:45:57,902] - Resmgr::initialize: KBE_ROOT=D:/kbengine-2.4.2/
  INFO root [2019-03-02 14:45:57,902] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine-2.4.2/kbe/res/;D:/kbengine-2.4.2/first_server_assets/;D:/kbengine-2.4.2/first_server_assets/scripts/;D:/kbengine-2.4.2/first_server_assets/res/
  INFO root [2019-03-02 14:45:57,903] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine-2.4.2/kbe/bin/server/
  INFO root [2019-03-02 14:45:57,937] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:20013 )
  INFO root [2019-03-02 14:45:57,938] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.0.148:20013, SOMAXCONN=128.
  INFO root [2019-03-02 14:45:57,944] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.148 ( 192.168.0.148:14061 )
  INFO root [2019-03-02 14:45:57,945] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.148:14061, SOMAXCONN=128.
  INFO root [2019-03-02 14:45:57,945] - server-configs:
  INFO root [2019-03-02 14:45:57,945] - 	internalTcpAddr : 192.168.0.148:14061
  INFO root [2019-03-02 14:45:57,945] - 	externalTcpAddr : 192.168.0.148:20013
  INFO root [2019-03-02 14:45:57,945] - 	componentID : 9000
  WARN root [2019-03-02 14:45:58,533] - invalid UID(0) <= 0, please check UID for environment! automatically set to 34643.
  INFO root [2019-03-02 14:45:58,832] - Components::findLogger: found logger, addr:192.168.0.148:14064
  INFO root [2019-03-02 14:45:58,832] - Components::addComponent: reset orderLog, uid=34643!
  INFO root [2019-03-02 14:45:58,833] - Components::addComponent[logger], uid=34643, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-03-02 14:45:58,841] - ---- loginapp Version: 2.4.2. ScriptVersion: 0.1.0. Pythoncore: 3.7.2. Protocol: 7DB67FD8A6CA6099F26F40C54BC962E0. Config: Debug X86. Built: 17:20:28 Feb 27 2019. AppID: 9000. UID: 34643. PID: 14284 ----
  INFO root [2019-03-02 14:45:58,842] - Server 19: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 2097151kB RAM
  INFO root [2019-03-02 14:45:58,842] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-03-02 14:45:58,843] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-03-02 14:45:59,071] - Script::install(): is successfully, Python=(3.7.2 (default, Feb 27 2019, 17:13:46) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-03-02 14:45:59,072] - Script::install(): KBExtra is successfully!
S_INFO root [2019-03-02 14:45:59,111] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-03-02 14:45:59,111] - TelnetServer server is running on port 31000
  INFO root [2019-03-02 14:46:00,161] - ---- loginapp is running ----
 DEBUG root [2019-03-02 14:46:00,162] - Components::process(): Request for the process of identity...
  WARN root [2019-03-02 14:46:06,400] - Forwarding logs to logger[192.168.0.148:14064/0/0/0]...
 ERROR root [2019-03-02 14:49:22,829] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

